## Topic: 1 Getting & knowing your data

In [ ]:
import pandas as pd

In [3]:
pd.read_csv(filepath_or_buffer='insurance.csv')

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
pd.read_csv(filepath_or_buffer=r'D:\Learn\ProITBridge\Python\Chap04-PythonDataAnalysis\insurance.csv')

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [12]:
# Reading a tab separated value
pd.read_csv(filepath_or_buffer=r'D:\Learn\ProITBridge\Python\Chap04-PythonDataAnalysis\data.tsv.txt',sep="\t")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [11]:
pd.read_table(filepath_or_buffer=r'D:\Learn\ProITBridge\Python\Chap04-PythonDataAnalysis\data.tsv.txt')

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [9]:
pd.read_table(filepath_or_buffer=r'D:\Learn\ProITBridge\Python\Chap04-PythonDataAnalysis\insurance.csv',sep=",")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [14]:
insurance_base_df = pd.read_csv(filepath_or_buffer=r'D:\Learn\ProITBridge\Python\Chap04-PythonDataAnalysis\insurance.csv')
insurance_base_df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [98]:
order_info_base_df = pd.read_csv(filepath_or_buffer=r'D:\Learn\ProITBridge\Python\Chap04-PythonDataAnalysis\data.tsv.txt',sep='\t')
order_info_base_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Perform Initial Analysis on the data

In [99]:
#df.shape returns the size(rows and coluns) of the dataframe
# rows => records or observations
# columns => features/parameters
order_info_base_df.shape

(4622, 5)

In [100]:
order_info_base_df.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [101]:
# chain of functions
order_info_base_df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [102]:
# describe() -> Generates descriptive statistics for the df
order_info_base_df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [103]:
order_info_base_df.describe(include = 'all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

### Find out the items sold in the restaurant

In [104]:
order_info_base_df.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [30]:
order_info_base_df["item_name"].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [105]:
items_list = list(order_info_base_df["item_name"].unique())
items_list

['Chips and Fresh Tomato Salsa',
 'Izze',
 'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
 'Chicken Bowl',
 'Side of Chips',
 'Steak Burrito',
 'Steak Soft Tacos',
 'Chips and Guacamole',
 'Chicken Crispy Tacos',
 'Chicken Soft Tacos',
 'Chicken Burrito',
 'Canned Soda',
 'Barbacoa Burrito',
 'Carnitas Burrito',
 'Carnitas Bowl',
 'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
 'Barbacoa Bowl',
 'Chips',
 'Chicken Salad Bowl',
 'Steak Bowl',
 'Barbacoa Soft Tacos',
 'Veggie Burrito',
 'Veggie Bowl',
 'Steak Crispy Tacos',
 'Chips and Tomatillo Red Chili Salsa',
 'Barbacoa Crispy Tacos',
 'Veggie Salad Bowl',
 'Chips and Roasted Chili-Corn Salsa',
 'Chips and Roasted Chili Corn Salsa',
 'Carnitas Soft Tacos',
 'Chicken Salad',
 'Canned Soft Drink',
 'Steak Salad Bowl',
 '6 Pack Soft Drink',
 'Chips and Tomatillo-Red Chili Salsa',
 'Bowl',
 'Burrito',
 'Crispy Tacos',
 'Carnitas Crispy Tacos',
 'Steak Salad',
 'Chips and Mild Fresh Tomato Salsa',
 'Veggie Soft Tacos',
 'Carnitas Salad Bowl',
 'Barbacoa Salad Bowl',
 'Salad',
 'Veggie Crispy Tacos',
 'Veggie Salad',
 'Carnitas Salad']

### find the top 5 selling items

In [106]:
order_info_base_df.groupby(by="item_name")["quantity"].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [107]:
order_info_base_df.groupby(by="item_name")["quantity"].sum().sort_values()

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [108]:
order_info_base_df.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [109]:
order_info_base_df.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False).head(10)

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

### finding least selling 5 items

In [110]:
order_info_base_df.groupby(by="item_name")["quantity"].sum().sort_values().head(5)

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

In [111]:
# Calculate revenue (quantity × price) by item, sum it, and get top 5
order_info_base_df.groupby("item_name").apply(
    lambda x: (x["quantity"] * x["item_price"]).sum()
).sort_values(ascending=False).head(5)

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_12928\2885558115.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  order_info_base_df.groupby("item_name").apply(

item_name
Carnitas Soft Tacos      $9.25 $9.25 $9.25 $9.25 $9.25 $8.99 $8.99 $8.9...
Barbacoa Soft Tacos      $9.25 $9.25 $8.99 $9.25 $9.25 $11.75 $11.75 $9...
Steak Soft Tacos         $9.25 $9.25 $8.99 $9.25 $8.99 $8.99 $9.25 $9.2...
Steak Crispy Tacos       $9.25 $8.99 $9.25 $8.69 $8.99 $9.25 $8.99 $9.2...
Carnitas Crispy Tacos    $9.25 $11.75 $8.99 $11.75 $8.99 $17.98 $17.98 ...
dtype: object

In [112]:
order_info_base_df.assign(
    revenue=order_info_base_df["quantity"] * 
            order_info_base_df["item_price"].str.replace("$", "").astype(float)
).groupby("item_name")["revenue"].sum().sort_values(ascending=False).head(5)

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: revenue, dtype: float64

In [113]:
order_info_base_df.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

### Data cleaning

In [114]:
order_info_base_df["item_price"]

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
         ...
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

In [115]:
order_info_base_df["item_price"].str.replace("$","")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [116]:
#This won't work as the object is returned as series and it doesn't have any attribute called float.
order_info_base_df["item_price"].str.replace("$","").float

AttributeError: 'Series' object has no attribute 'float'

In [117]:
order_info_base_df["item_price"].str.replace("$","").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [118]:
order_info_base_df["item_price"] = order_info_base_df["item_price"].str.replace("$","").astype(float)
order_info_base_df.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [119]:
order_info_base_df.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [120]:
order_info_base_df.groupby("item_name").apply(
    lambda x: (x["quantity"] * x["item_price"]).sum()
).sort_values(ascending=False).head(5)

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_12928\1016425235.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  order_info_base_df.groupby("item_name").apply(

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
dtype: float64

In [121]:
order_info_base_df.groupby("item_name").apply(
    lambda x: (x["quantity"] * x["item_price"]).sum()
).sort_values(ascending=False).head(5).sum()

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_12928\1500336645.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  order_info_base_df.groupby("item_name").apply(

np.float64(23623.25)

In [122]:
order_info_base_df.assign(
    revenue=order_info_base_df["quantity"] * 
            order_info_base_df["item_price"]
).groupby("item_name")["revenue"].sum().sort_values(ascending=False).head(5)

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: revenue, dtype: float64

In [123]:
order_info_base_df.assign(
    revenue=order_info_base_df["quantity"] * 
            order_info_base_df["item_price"]
).groupby("item_name")["revenue"].sum().sort_values(ascending=False).head(5).sum()

np.float64(23623.25)

In [124]:
order_info_base_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

### Pandas Data Structures

1. Series (1 dimention)
2. Data Frames (2 dimention)

In [83]:
#Series always return data with index and the index starts with 0
pd.Series(data=1)

0    1
dtype: int64

In [85]:
# Series of data using python tuple
pd.Series(data=(1,2))

0    1
1    2
dtype: int64

In [86]:
# Series of data using python list
pd.Series(data=[0,1,2,3,5])

0    0
1    1
2    2
3    3
4    5
dtype: int64

In [88]:
pd.Series(data={0,1,2,3,5})

TypeError: 'set' type is unordered

In [90]:
#SSet is a two dimentional data can be processed using DataFrame
pd.DataFrame(data={0,1,2,3,5})

   0
0  0
1  1
2  2
3  3
4  5

In [92]:
pd.DataFrame(data=[1,2,3,4,5,6])

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [95]:
pd.DataFrame(data={"Names":["nanda","kumar","govindan"],"age":[44,46,45]})

      Names  age
0     nanda   44
1     kumar   46
2  govindan   45

## Filtering rows, field/columns selections and Sorting

In [128]:
df_eruo_2012_data = pd.read_csv(filepath_or_buffer='Euro 2012 stats Team.csv')
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [129]:
df_eruo_2012_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [130]:
pd.set_option('display.max_columns',None)
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

In [131]:
pd.set_option('display.max_columns',20)
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [132]:
pd.set_option('display.max_columns',10)
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
3,England,5,11,18,50.0%,...,5,0,11,11,16
4,France,3,22,24,37.9%,...,6,0,11,11,19
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18

In [133]:
pd.set_option('display.max_rows',10)
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
3,England,5,11,18,50.0%,...,5,0,11,11,16
4,France,3,22,24,37.9%,...,6,0,11,11,19
...,...,...,...,...,...,...,...,...,...,...,...
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18

In [134]:
pd.set_option('display.max_rows',None)
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
3,England,5,11,18,50.0%,...,5,0,11,11,16
4,France,3,22,24,37.9%,...,6,0,11,11,19
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18

In [135]:
df_eruo_2012_data["Team"]

0                 Croatia
1          Czech Republic
2                 Denmark
3                 England
4                  France
5                 Germany
6                  Greece
7                   Italy
8             Netherlands
9                  Poland
10               Portugal
11    Republic of Ireland
12                 Russia
13                  Spain
14                 Sweden
15                Ukraine
Name: Team, dtype: object

In [136]:
#This won't work
df_eruo_2012_data["Team","Goals"]

KeyError: ('Team', 'Goals')

In [137]:
df_eruo_2012_data[["Team","Goals"]]

                   Team  Goals
0               Croatia      4
1        Czech Republic      4
2               Denmark      4
3               England      5
4                France      3
5               Germany     10
6                Greece      5
7                 Italy      6
8           Netherlands      2
9                Poland      2
10             Portugal      6
11  Republic of Ireland      1
12               Russia      5
13                Spain     12
14               Sweden      5
15              Ukraine      2

In [138]:
df_eruo_2012_data[["Team","Goals","Yellow Cards","Red Cards"]]

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [140]:
df_eruo_2012_data_filtered = df_eruo_2012_data[["Team","Goals","Red Cards","Yellow Cards"]]
df_eruo_2012_data_filtered

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [141]:
df_eruo_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
3,England,5,11,18,50.0%,...,5,0,11,11,16
4,France,3,22,24,37.9%,...,6,0,11,11,19
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18

In [142]:
df_eruo_2012_data.sort_values(by = "Yellow Cards", ascending = False)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17
4,France,3,22,24,37.9%,...,6,0,11,11,19
3,England,5,11,18,50.0%,...,5,0,11,11,16
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15

In [143]:
df_eruo_2012_data.sort_values(by = "Goals", ascending = False)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
3,England,5,11,18,50.0%,...,5,0,11,11,16
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
4,France,3,22,24,37.9%,...,6,0,11,11,19
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17

In [147]:
df_eruo_2012_data.sort_values(by = ["Goals","Team"], ascending = False)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
3,England,5,11,18,50.0%,...,5,0,11,11,16
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
4,France,3,22,24,37.9%,...,6,0,11,11,19
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17

In [148]:
df_eruo_2012_data.sort_values(by=["Goals", "Team"], ascending=[False, True])

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
3,England,5,11,18,50.0%,...,5,0,11,11,16
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
4,France,3,22,24,37.9%,...,6,0,11,11,19
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17

### Filtering rows

In [152]:
#List the teams who scored 6 Goals
df_eruo_2012_data["Goals"]==6

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
Name: Goals, dtype: bool

In [153]:
#List the teams who scored 6 Goals
df_eruo_2012_data[df_eruo_2012_data["Goals"]==6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16

In [155]:
# Applying multiple conditions with AND
df_eruo_2012_data[(df_eruo_2012_data["Goals"]==6) & (df_eruo_2012_data["Yellow Cards"]==16)]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,...,16,0,18,18,19

In [157]:
# Applying multiple conditions with OR
df_eruo_2012_data[(df_eruo_2012_data["Goals"]==6) | (df_eruo_2012_data["Yellow Cards"]>10)]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18

In [158]:
#List the teams who scored 6 Goals --another method using df.loc[]
df_eruo_2012_data.loc[df_eruo_2012_data["Goals"]==6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16

In [160]:
# applying filter with in condition
df_eruo_2012_data[df_eruo_2012_data["Team"].isin(['Italy','German','Spain'])]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
13,Spain,12,42,33,55.9%,...,11,0,17,17,18

In [162]:
# applying filter using str.startswith
df_eruo_2012_data[df_eruo_2012_data["Team"].str.startswith("S")]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18

In [163]:
# applying filter using isnull
df_eruo_2012_data[df_eruo_2012_data["Team"].isnull()]

Empty DataFrame
Columns: [Team, Goals, Shots on target, Shots off target, Shooting Accuracy, % Goals-to-shots, Total shots (inc. Blocked), Hit Woodwork, Penalty goals, Penalties not scored, Headed goals, Passes, Passes completed, Passing Accuracy, Touches, Crosses, Dribbles, Corners Taken, Tackles, Clearances, Interceptions, Clearances off line, Clean Sheets, Blocks, Goals conceded, Saves made, Saves-to-shots ratio, Fouls Won, Fouls Conceded, Offsides, Yellow Cards, Red Cards, Subs on, Subs off, Players Used]
Index: []

[0 rows x 35 columns]

In [165]:
# applying filter using notnull
df_eruo_2012_data[df_eruo_2012_data["Team"].notnull()]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
3,England,5,11,18,50.0%,...,5,0,11,11,16
4,France,3,22,24,37.9%,...,6,0,11,11,19
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
6,Greece,5,8,18,30.7%,...,9,1,12,12,20
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,...,5,0,7,7,15
9,Poland,2,15,23,39.4%,...,7,1,7,7,17
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,...,6,1,10,10,17
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,...,5,0,9,9,18

In [168]:
#Filtering using query option
df_eruo_2012_data.query("Goals > 3 and `Red Cards` < 1")

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,...,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,...,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,...,7,0,11,11,19
2,Denmark,4,10,10,50.0%,...,4,0,7,7,15
3,England,5,11,18,50.0%,...,5,0,11,11,16
5,Germany,10,32,32,47.8%,...,4,0,15,15,17
7,Italy,6,34,45,43.0%,...,16,0,18,18,19
10,Portugal,6,22,42,34.3%,...,12,0,14,14,16
12,Russia,5,9,31,22.5%,...,6,0,7,7,16
13,Spain,12,42,33,55.9%,...,11,0,17,17,18
14,Sweden,5,17,19,47.2%,...,7,0,9,9,18

## Task 3a
### Conceptual Questions

### 1.	Why is Python preferred in the field of Data Science?
Answer:
Python dominates data science because it balances ease of use with powerful capabilities. It allows data scientists to focus on solving problems rather than dealing with language complexity. The combination of simple syntax, rich libraries, community support, and industry adoption makes Python the go-to choice for data science projects.

1. Easy to Learn and Read
2. Rich Ecosystem of Libraries
3. Versatility
4. Community and Support
5. Integration Capabilities
6. Performance
7. Open Source and Free
8. Industry Standard
9. Scalability

### 2.	What is the difference between a Jupyter Notebook and Google Colab?

Jupyter Notebook is an open-source web application that allows you to create and share documents containing live code, equations, visualizations, and narrative text.

Key Characteristics

Interactive coding environment - Write and run code in cells
Mixed content - Combine code, text, images, and visualizations
Runs locally - On your own computer
Browser-based - Accessed through a web browser
Language-agnostic - Supports Python, R, Julia, and 40+ languages


Google Colab is a free cloud-based version of Jupyter Notebook hosted by Google. It runs on Google's servers, so you don't need to install anything.

Key Characteristics

Cloud-based - Runs on Google's servers
Free to use - No installation or setup required
Built-in GPU/TPU - For deep learning and heavy computations
Google Drive integration - Automatic saving
Real-time collaboration - Like Google Docs
Browser-only - Access from anywhere


0. Feature                    ### Jupyter Notebook                    ### Google Colab
1. Installation               ### Requires local setup                ### Cloud-based, no setup
2. Cost                       ### Free                                ### Free (with paid options)
3. Hardware                   ### Your computer                       ### Google's servers (GPU/TPU available)
4. Storage                    ### Local file system                   ### Google Drive integration
5. Collaboration              ### Manual sharing                      ### Built-in real-time collaboration
6. Accessibility              ### Only on your machine                ### Access from anywhere
7. Performance                ### Depends on your PC                  ### Powerful cloud resources
8. Internet                   ### Not required                        ### Required
9. Preinstalled Libraries     ### Minimal                             ### Many ML libraries pre-installed

### 3.	When would you use a list over a set or a tuple?
1. List: Data changes frequently and order matters
2. Set: Need unique values and fast lookups
3. Tuple: Data is fixed or needs to be a dictionary key

### 4.	What is exception handling? Give a real-life example of when it's useful

Exception Handling in Python
What is Exception Handling?
Exception handling is a mechanism to gracefully handle errors that occur during program execution instead of letting the program crash.

Without Exception Handling (Program Crashes)

In [169]:
#The below example access the withdrawal amount and shows the new balance post withdrawal

def withdraw_money(account_balance):
    try:
        # Get user input
        amount_str = input("Enter withdrawal amount: $")
        amount = float(amount_str)
        
        # Check for negative amount
        if amount <= 0:
            raise ValueError("Amount must be positive")
        
        # Check sufficient balance
        if amount > account_balance:
            raise ValueError(f"Insufficient funds. Balance: ${account_balance}")
        
        # Process withdrawal
        new_balance = account_balance - amount
        print(f"Withdrawal successful!")
        print(f"New balance: ${new_balance}")
        return new_balance
        
    except ValueError as e:
        print(f"Input Error: {e}")
        return account_balance
        
    except Exception as e:
        print(f"Unexpected error: {e}")
        return account_balance

# Test cases
balance = withdraw_money(500)  # User enters "100" → Success

Enter withdrawal amount: $ 500

✓ Withdrawal successful!
New balance: $0.0

In [170]:
balance = withdraw_money(500)  # User enters "abc" → ValueError

Enter withdrawal amount: $ abc

Input Error: could not convert string to float: 'abc'

In [171]:
balance = withdraw_money(500)  # User enters "600" → Insufficient funds

Enter withdrawal amount: $ 1000

Input Error: Insufficient funds. Balance: $500

### 5.	Define DataFrame and Series in Pandas. What’s the difference?

In [172]:
#DataFrame and Series in Pandas - Simple Explanation
#Series
#Definition
#A Series is a one-dimensional array of data with labels (index).
#Think of it as a single column in a spreadsheet or a list with labels.

#Series (like a single column):

#Index    Data
#0        10
#1        20
#2        30
#3        40

import pandas as pd

# Method 1: From a list
scores = pd.Series([85, 90, 88, 92])
print(scores)

0    85
1    90
2    88
3    92
dtype: int64

In [173]:
# Method 2: With custom labels (index)
scores = pd.Series([85, 90, 88, 92], index=['Alice', 'Bob', 'Charlie', 'David'])
print(scores)

Alice      85
Bob        90
Charlie    88
David      92
dtype: int64

In [174]:
# Method 3: From a dictionary
scores = pd.Series({'Alice': 85, 'Bob': 90, 'Charlie': 88})
print(scores)

Alice      85
Bob        90
Charlie    88
dtype: int64

In [175]:
# Accessing a Series
# By position (like a list)
print(scores[0])      # Output: 85

85

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_12928\58927931.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(scores[0])      # Output: 85

In [176]:
# Accessing a Series
# By label (like a dictionary)
print(scores['Alice'])  # Output: 85

85

In [177]:
# Accessing a Series
# Multiple values
print(scores[0:2])    # Output: First 2 rows

Alice    85
Bob      90
dtype: int64

In [178]:
#DataFrame
#Definition
#A DataFrame is a two-dimensional table with rows and columns.
#Think of it as a spreadsheet or a collection of Series.

#DataFrame (like a spreadsheet):

#      Name      Age    Score   City
#0     Alice     25      85    NYC
#1     Bob       30      90    LA
#2     Charlie   28      88    Chicago
#3     David     35      92    Boston

import pandas as pd

# Method 1: From a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 28, 35],
    'Score': [85, 90, 88, 92]
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   28     88
3    David   35     92

In [179]:
# Method 2: From a list of lists
data = [
    ['Alice', 25, 85],
    ['Bob', 30, 90],
    ['Charlie', 28, 88]
]
df = pd.DataFrame(data, columns=['Name', 'Age', 'Score'])
print(df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   28     88

In [182]:
# Method 3: From a CSV file
insurance_df = pd.read_csv('insurance.csv')
insurance_df

      age     sex     bmi  children smoker     region       charges
0      19  female  27.900         0    yes  southwest  16884.924000
1      18    male  33.770         1     no  southeast   1725.552300
2      28    male  33.000         3     no  southeast   4449.462000
3      33    male  22.705         0     no  northwest  21984.470610
4      32    male  28.880         0     no  northwest   3866.855200
5      31  female  25.740         0     no  southeast   3756.621600
6      46  female  33.440         1     no  southeast   8240.589600
7      37  female  27.740         3     no  northwest   7281.505600
8      37    male  29.830         2     no  northeast   6406.410700
9      60  female  25.840         0     no  northwest  28923.136920
10     25    male  26.220         0     no  northeast   2721.320800
11     62  female  26.290         0    yes  southeast  27808.725100
12     23    male  34.400         0     no  southwest   1826.843000
13     56  female  39.820         0     no  southeast  11090.717800
14     27    male  42.130         0    yes  southeast  39611.757700
15     19    male  24.600         1     no  southwest   1837.237000
16     52  female  30.780         1     no  northeast  10797.336200
17     23    male  23.845         0     no  northeast   2395.171550
18     56    male  40.300         0     no  southwest  10602.385000
19     30    male  35.300         0    yes  southwest  36837.467000
20     60  female  36.005         0     no  northeast  13228.846950
21     30  female  32.400         1     no  southwest   4149.736000
22     18    male  34.100         0     no  southeast   1137.011000
23     34  female  31.920         1    yes  northeast  37701.876800
24     37    male  28.025         2     no  northwest   6203.901750
25     59  female  27.720         3     no  southeast  14001.133800
26     63  female  23.085         0     no  northeast  14451.835150
27     55  female  32.775         2     no  northwest  12268.632250
28     23    male  17.385         1     no  northwest   2775.192150
29     31    male  36.300         2    yes  southwest  38711.000000
30     22    male  35.600         0    yes  southwest  35585.576000
31     18  female  26.315         0     no  northeast   2198.189850
32     19  female  28.600         5     no  southwest   4687.797000
33     63    male  28.310         0     no  northwest  13770.097900
34     28    male  36.400         1    yes  southwest  51194.559140
35     19    male  20.425         0     no  northwest   1625.433750
36     62  female  32.965         3     no  northwest  15612.193350
37     26    male  20.800         0     no  southwest   2302.300000
38     35    male  36.670         1    yes  northeast  39774.276300
39     60    male  39.900         0    yes  southwest  48173.361000
40     24  female  26.600         0     no  northeast   3046.062000
41     31  female  36.630         2     no  southeast   4949.758700
42     41    male  21.780         1     no  southeast   6272.477200
43     37  female  30.800         2     no  southeast   6313.759000
44     38    male  37.050         1     no  northeast   6079.671500
45     55    male  37.300         0     no  southwest  20630.283510
46     18  female  38.665         2     no  northeast   3393.356350
47     28  female  34.770         0     no  northwest   3556.922300
48     60  female  24.530         0     no  southeast  12629.896700
49     36    male  35.200         1    yes  southeast  38709.176000
50     18  female  35.625         0     no  northeast   2211.130750
51     21  female  33.630         2     no  northwest   3579.828700
52     48    male  28.000         1    yes  southwest  23568.272000
53     36    male  34.430         0    yes  southeast  37742.575700
54     40  female  28.690         3     no  northwest   8059.679100
55     58    male  36.955         2    yes  northwest  47496.494450
56     58  female  31.825         2     no  northeast  13607.368750
57     18    male  31.680         2    yes  southeast  34303.167200
58     53  female  22.880         1    yes  southeast  23244.790200
59     34  female  37.335         2     no  northwest   5989.523650
60     43    male  27.360         3     no  northeast   8606.217400
61     25    male  33.660         4     no  southeast   4504.662400
62     64    male  24.700         1     no  northwest  30166.618170
63     28  female  25.935         1     no  northwest   4133.641650
64     20  female  22.420         0    yes  northwest  14711.743800
65     19  female  28.900         0     no  southwest   1743.214000
66     61  female  39.100         2     no  southwest  14235.072000
67     40    male  26.315         1     no  northwest   6389.377850
68     40  female  36.190         0     no  southeast   5920.104100
69     28    male  23.980         3    yes  southeast  17663.144200
70     27  female  24.750         0    yes  southeast  16577.779500
71     31    male  28.500         5     no  northeast   6799.458000
72     53  female  28.100         3     no  southwest  11741.726000
73     58    male  32.010         1     no  southeast  11946.625900
74     44    male  27.400         2     no  southwest   7726.854000
75     57    male  34.010         0     no  northwest  11356.660900
76     29  female  29.590         1     no  southeast   3947.413100
77     21    male  35.530         0     no  southeast   1532.469700
78     22  female  39.805         0     no  northeast   2755.020950
79     41  female  32.965         0     no  northwest   6571.024350
80     31    male  26.885         1     no  northeast   4441.213150
81     45  female  38.285         0     no  northeast   7935.291150
82     22    male  37.620         1    yes  southeast  37165.163800
83     48  female  41.230         4     no  northwest  11033.661700
84     37  female  34.800         2    yes  southwest  39836.519000
85     45    male  22.895         2    yes  northwest  21098.554050
86     57  female  31.160         0    yes  northwest  43578.939400
87     56  female  27.200         0     no  southwest  11073.176000
88     46  female  27.740         0     no  northwest   8026.666600
89     55  female  26.980         0     no  northwest  11082.577200
90     21  female  39.490         0     no  southeast   2026.974100
91     53  female  24.795         1     no  northwest  10942.132050
92     59    male  29.830         3    yes  northeast  30184.936700
93     35    male  34.770         2     no  northwest   5729.005300
94     64  female  31.300         2    yes  southwest  47291.055000
95     28  female  37.620         1     no  southeast   3766.883800
96     54  female  30.800         3     no  southwest  12105.320000
97     55    male  38.280         0     no  southeast  10226.284200
98     56    male  19.950         0    yes  northeast  22412.648500
99     38    male  19.300         0    yes  southwest  15820.699000
100    41  female  31.600         0     no  southwest   6186.127000
101    30    male  25.460         0     no  northeast   3645.089400
102    18  female  30.115         0     no  northeast  21344.846700
103    61  female  29.920         3    yes  southeast  30942.191800
104    34  female  27.500         1     no  southwest   5003.853000
105    20    male  28.025         1    yes  northwest  17560.379750
106    19  female  28.400         1     no  southwest   2331.519000
107    26    male  30.875         2     no  northwest   3877.304250
108    29    male  27.940         0     no  southeast   2867.119600
109    63    male  35.090         0    yes  southeast  47055.532100
110    54    male  33.630         1     no  northwest  10825.253700
111    55  female  29.700         2     no  southwest  11881.358000
112    37    male  30.800         0     no  southwest   4646.759000
113    21  female  35.720         0     no  northwest   2404.733800
114    52    male  32.205         3     no  northeast  11488.316950
115    60    male  28.595         0     no  northeast  30259.995560
116    58    male  49.060         0     no  southeast  11381.325400
117    29  female  27.940         1    yes  southeast  19107.779600
118    49  female  27.170         0     no  southeast   8601.329300
119    37  female  23.370         2     no  northwest   6686.431300
120    44    male  37.100         2     no  southwest   7740.337000
121    18    male  23.750         0     no  northeast   1705.624500
122    20  female  28.975         0     no  northwest   2257.475250
123    44    male  31.350         1    yes  northeast  39556.494500
124    47  female  33.915         3     no  northwest  10115.008850
125    26  female  28.785         0     no  northeast   3385.399150
126    19  female  28.300         0    yes  southwest  17081.080000
127    52  female  37.400         0     no  southwest   9634.538000
128    32  female  17.765         2    yes  northwest  32734.186300
129    38    male  34.700         2     no  southwest   6082.405000
130    59  female  26.505         0     no  northeast  12815.444950
131    61  female  22.040         0     no  northeast  13616.358600
132    53  female  35.900         2     no  southwest  11163.568000
133    19    male  25.555         0     no  northwest   1632.564450
134    20  female  28.785         0     no  northeast   2457.211150
135    22  female  28.050         0     no  southeast   2155.681500
136    19    male  34.100         0     no  southwest   1261.442000
137    22    male  25.175         0     no  northwest   2045.685250
138    54  female  31.900         3     no  southeast  27322.733860
139    22  female  36.000         0     no  southwest   2166.732000
140    34    male  22.420         2     no  northeast  27375.904780
141    26    male  32.490         1     no  northeast   3490.549100
142    34    male  25.300         2    yes  southeast  18972.495000
143    29    male  29.735         2     no  northwest  18157.876000
144    30    male  28.690         3    yes  northwest  20745.989100
145    29  female  38.830         3     no  southeast   5138.256700
146    46    male  30.495         3    yes  northwest  40720.551050
147    51  female  37.730         1     no  southeast   9877.607700
148    53  female  37.430         1     no  northwest  10959.694700
149    19    male  28.400         1     no  southwest   1842.519000
150    35    male  24.130         1     no  northwest   5125.215700
151    48    male  29.700         0     no  southeast   7789.635000
152    32  female  37.145         3     no  northeast   6334.343550
153    42  female  23.370         0    yes  northeast  19964.746300
154    40  female  25.460         1     no  northeast   7077.189400
155    44    male  39.520         0     no  northwest   6948.700800
156    48    male  24.420         0    yes  southeast  21223.675800
157    18    male  25.175         0    yes  northeast  15518.180250
158    30    male  35.530         0    yes  southeast  36950.256700
159    50  female  27.830         3     no  southeast  19749.383380
160    42  female  26.600         0    yes  northwest  21348.706000
161    18  female  36.850         0    yes  southeast  36149.483500
162    54    male  39.600         1     no  southwest  10450.552000
163    32  female  29.800         2     no  southwest   5152.134000
164    37    male  29.640         0     no  northwest   5028.146600
165    47    male  28.215         4     no  northeast  10407.085850
166    20  female  37.000         5     no  southwest   4830.630000
167    32  female  33.155         3     no  northwest   6128.797450
168    19  female  31.825         1     no  northwest   2719.279750
169    27    male  18.905         3     no  northeast   4827.904950
170    63    male  41.470         0     no  southeast  13405.390300
171    49    male  30.300         0     no  southwest   8116.680000
172    18    male  15.960         0     no  northeast   1694.796400
173    35  female  34.800         1     no  southwest   5246.047000
174    24  female  33.345         0     no  northwest   2855.437550
175    63  female  37.700         0    yes  southwest  48824.450000
176    38    male  27.835         2     no  northwest   6455.862650
177    54    male  29.200         1     no  southwest  10436.096000
178    46  female  28.900         2     no  southwest   8823.279000
179    41  female  33.155         3     no  northeast   8538.288450
180    58    male  28.595         0     no  northwest  11735.879050
181    18  female  38.280         0     no  southeast   1631.821200
182    22    male  19.950         3     no  northeast   4005.422500
183    44  female  26.410         0     no  northwest   7419.477900
184    44    male  30.690         2     no  southeast   7731.427100
185    36    male  41.895         3    yes  northeast  43753.337050
186    26  female  29.920         2     no  southeast   3981.976800
187    30  female  30.900         3     no  southwest   5325.651000
188    41  female  32.200         1     no  southwest   6775.961000
189    29  female  32.110         2     no  northwest   4922.915900
190    61    male  31.570         0     no  southeast  12557.605300
191    36  female  26.200         0     no  southwest   4883.866000
192    25    male  25.740         0     no  southeast   2137.653600
193    56  female  26.600         1     no  northwest  12044.342000
194    18    male  34.430         0     no  southeast   1137.469700
195    19    male  30.590         0     no  northwest   1639.563100
196    39  female  32.800         0     no  southwest   5649.715000
197    45  female  28.600         2     no  southeast   8516.829000
198    51  female  18.050         0     no  northwest   9644.252500
199    64  female  39.330         0     no  northeast  14901.516700
200    19  female  32.110         0     no  northwest   2130.675900
201    48  female  32.230         1     no  southeast   8871.151700
202    60  female  24.035         0     no  northwest  13012.208650
203    27  female  36.080         0    yes  southeast  37133.898200
204    46    male  22.300         0     no  southwest   7147.105000
205    28  female  28.880         1     no  northeast   4337.735200
206    59    male  26.400         0     no  southeast  11743.299000
207    35    male  27.740         2    yes  northeast  20984.093600
208    63  female  31.800         0     no  southwest  13880.949000
209    40    male  41.230         1     no  northeast   6610.109700
210    20    male  33.000         1     no  southwest   1980.070000
211    40    male  30.875         4     no  northwest   8162.716250
212    24    male  28.500         2     no  northwest   3537.703000
213    34  female  26.730         1     no  southeast   5002.782700
214    45  female  30.900         2     no  southwest   8520.026000
215    41  female  37.100         2     no  southwest   7371.772000
216    53  female  26.600         0     no  northwest  10355.641000
217    27    male  23.100         0     no  southeast   2483.736000
218    26  female  29.920         1     no  southeast   3392.976800
219    24  female  23.210         0     no  southeast  25081.767840
220    34  female  33.700         1     no  southwest   5012.471000
221    53  female  33.250         0     no  northeast  10564.884500
222    32    male  30.800         3     no  southwest   5253.524000
223    19    male  34.800         0    yes  southwest  34779.615000
224    42    male  24.640         0    yes  southeast  19515.541600
225    55    male  33.880         3     no  southeast  11987.168200
226    28    male  38.060         0     no  southeast   2689.495400
227    58  female  41.910         0     no  southeast  24227.337240
228    41  female  31.635         1     no  northeast   7358.175650
229    47    male  25.460         2     no  northeast   9225.256400
230    42  female  36.195         1     no  northwest   7443.643050
231    59  female  27.830         3     no  southeast  14001.286700
232    19  female  17.800         0     no  southwest   1727.785000
233    59    male  27.500         1     no  southwest  12333.828000
234    39    male  24.510         2     no  northwest   6710.191900
235    40  female  22.220         2    yes  southeast  19444.265800
236    18  female  26.730         0     no  southeast   1615.766700
237    31    male  38.390         2     no  southeast   4463.205100
238    19    male  29.070         0    yes  northwest  17352.680300
239    44    male  38.060         1     no  southeast   7152.671400
240    23  female  36.670         2    yes  northeast  38511.628300
241    33  female  22.135         1     no  northeast   5354.074650
242    55  female  26.800         1     no  southwest  35160.134570
243    40    male  35.300         3     no  southwest   7196.867000
244    63  female  27.740         0    yes  northeast  29523.165600
245    54    male  30.020         0     no  northwest  24476.478510
246    60  female  38.060         0     no  southeast  12648.703400
247    24    male  35.860         0     no  southeast   1986.933400
248    19    male  20.900         1     no  southwest   1832.094000
249    29    male  28.975         1     no  northeast   4040.558250
250    18    male  17.290         2    yes  northeast  12829.455100
251    63  female  32.200         2    yes  southwest  47305.305000
252    54    male  34.210         2    yes  southeast  44260.749900
253    27    male  30.300         3     no  southwest   4260.744000
254    50    male  31.825         0    yes  northeast  41097.161750
255    55  female  25.365         3     no  northeast  13047.332350
256    56    male  33.630         0    yes  northwest  43921.183700
257    38  female  40.150         0     no  southeast   5400.980500
258    51    male  24.415         4     no  northwest  11520.099850
259    19    male  31.920         0    yes  northwest  33750.291800
260    58  female  25.200         0     no  southwest  11837.160000
261    20  female  26.840         1    yes  southeast  17085.267600
262    52    male  24.320         3    yes  northeast  24869.836800
263    19    male  36.955         0    yes  northwest  36219.405450
264    53  female  38.060         3     no  southeast  20462.997660
265    46    male  42.350         3    yes  southeast  46151.124500
266    40    male  19.800         1    yes  southeast  17179.522000
267    59  female  32.395         3     no  northeast  14590.632050
268    45    male  30.200         1     no  southwest   7441.053000
269    49    male  25.840         1     no  northeast   9282.480600
270    18    male  29.370         1     no  southeast   1719.436300
271    50    male  34.200         2    yes  southwest  42856.838000
272    41    male  37.050         2     no  northwest   7265.702500
273    50    male  27.455         1     no  northeast   9617.662450
274    25    male  27.550         0     no  northwest   2523.169500
275    47  female  26.600         2     no  northeast   9715.841000
276    19    male  20.615         2     no  northwest   2803.697850
277    22  female  24.300         0     no  southwest   2150.469000
278    59    male  31.790         2     no  southeast  12928.791100
279    51  female  21.560         1     no  southeast   9855.131400
280    40  female  28.120         1    yes  northeast  22331.566800
281    54    male  40.565         3    yes  northeast  48549.178350
282    30    male  27.645         1     no  northeast   4237.126550
283    55  female  32.395         1     no  northeast  11879.104050
284    52  female  31.200         0     no  southwest   9625.920000
285    46    male  26.620         1     no  southeast   7742.109800
286    46  female  48.070         2     no  northeast   9432.925300
287    63  female  26.220         0     no  northwest  14256.192800
288    59  female  36.765         1    yes  northeast  47896.791350
289    52    male  26.400         3     no  southeast  25992.821040
290    28  female  33.400         0     no  southwest   3172.018000
291    29    male  29.640         1     no  northeast  20277.807510
292    25    male  45.540         2    yes  southeast  42112.235600

In [184]:
# Accessing Data in DataFrame
# Single column (returns a Series)
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 28, 35],
    'Score': [85, 90, 88, 92]
}
df = pd.DataFrame(data)
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [185]:
# Multiple columns (returns a DataFrame)
print(df[['Name', 'Score']])

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     88
3    David     92

In [186]:
# Single row by position
print(df.iloc[0])

Name     Alice
Age         25
Score       85
Name: 0, dtype: object

In [187]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 90, 88],
    'English': [92, 85, 90],
    'Science': [88, 92, 91]
})
print(df)

# Extract a Series (one column)
math_scores = df['Math']
print(math_scores)

# This Series has one dimension!
print(type(math_scores))  # <class 'pandas.core.series.Series'>

# Extract a DataFrame (multiple columns)
scores = df[['Math', 'English']]
print(scores)

# This is still a DataFrame (2D)!
print(type(scores))  # <class 'pandas.core.frame.DataFrame'>

   Student  Math  English  Science
0    Alice    85       92       88
1      Bob    90       85       92
2  Charlie    88       90       91
0    85
1    90
2    88
Name: Math, dtype: int64
<class 'pandas.core.series.Series'>
   Math  English
0    85       92
1    90       85
2    88       90
<class 'pandas.core.frame.DataFrame'>

In [190]:
# SERIES
s = pd.Series([10, 20, 30, 40])
print(s.shape)          # (4,) - one dimension
print(len(s))           # 4 - number of elements
print(s[0])             # 10 - single value
print(s.mean())         # 25 - calculate mean

# DATAFRAME
df = pd.DataFrame({'A': [10, 20], 'B': [30, 40]})
print(df.shape)         # (2, 2) - 2 rows, 2 columns
print(df.columns)       # Index(['A', 'B'])
print(df['A'])          # Returns a Series
print(df.loc[0])        # Returns a Series (one row)
print(df.iloc[0, 0])    # Returns a scalar (single value)

(4,)
4
10
25.0
(2, 2)
Index(['A', 'B'], dtype='object')
0    10
1    20
Name: A, dtype: int64
A    10
B    30
Name: 0, dtype: int64
10

When to Use Each

0. Use Case 

1. Single column of data then use "Series".
2. Multiple columns (table data) then use "DataFrame".
3. Store scores of one student    then use "Series".
4. Store data for multiple students then use "DataFrame".
5. Time series (one metric over time) then use "Series".
6. Stock data (multiple metrics) then use "DataFrame".

### What are the different ways of dealing with missing values in a dataset?

1. Detection - Identify Missing Values
1.1 Methods to Find Missing Values
   df.isnull(), df.isna(), df.notnull(), df.isnull().sum(), df.isnull().sum().sum()

In [191]:
import pandas as pd
import numpy as np

# Create sample data with missing values
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', None, 'David'],
    'Age': [25, np.nan, 28, 35],
    'Score': [85, 90, None, 92]
})

print(df)


# Check for missing values
print(df.isnull())        # Shows True/False for each cell
print(df.isna())          # Same as isnull()
print(df.notnull())       # Opposite of isnull()

# Count missing values
print(df.isnull().sum())  # Count per column

# Total missing values
print(df.isnull().sum().sum())  # Total: 2

# Percentage of missing data
print(df.isnull().sum() / len(df) * 100)

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
2   None  28.0    NaN
3  David  35.0   92.0
    Name    Age  Score
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False
    Name    Age  Score
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False
    Name    Age  Score
0   True   True   True
1   True  False   True
2  False   True  False
3   True   True   True
Name     1
Age      1
Score    1
dtype: int64
3
Name     25.0
Age      25.0
Score    25.0
dtype: float64

In [192]:
### 2. Removal - Delete Missing Values

In [194]:
# Method 1: Remove rows with any missing value
Method 3: Remove columns with missing values
python# Remove columns with ANY missing value
df_clean = df.dropna(axis=1)
print(df_clean)# Original data
print(f"Original shape: {df.shape}")  # (4, 3)

# Remove rows with ANY missing value
df_clean = df.dropna()
print(f"After dropna(): {df_clean.shape}")  # (2, 3)

print(df_clean)

Original shape: (4, 3)
After dropna(): (2, 3)
    Name   Age  Score
0  Alice  25.0   85.0
3  David  35.0   92.0

In [196]:
# Method 2: Remove rows with missing in specific column
# Remove rows where Age is missing
df_clean = df.dropna(subset=['Age'])
print(df_clean)

    Name   Age  Score
0  Alice  25.0   85.0
2   None  28.0    NaN
3  David  35.0   92.0

In [197]:
# Method 3: Remove columns with missing values
# Remove columns with ANY missing value
df_clean = df.dropna(axis=1)
print(df_clean)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [198]:
#Method 4: Remove only if majority is missing
# Remove rows where >50% values are missing
df_clean = df.dropna(thresh=2)  # Keep rows with at least 2 non-null values
print(df_clean)

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
3  David  35.0   92.0

### 7.	How do NumPy and Pandas differ in terms of functionality?

In [199]:
#Feature           NumPy                          Pandas
#Dimensions        N-dimensional arrays           1D (Series) & 2D (DataFrame)
#Data Type         Homogeneous (same type)        Heterogeneous (mixed types)
#Labels            No labels (index-based)        Has row & column labels
#Structure         Array/Matrix                   Series/DataFrame (tabular)
#Use Case          Mathematical/scientific        Data analysis/manipulation
#Performance       Faster (C-based)               Slower (built on NumPy)
#Data Handling      Raw numerical data            Real-world messy data

### 8.	What is the role of libraries like Seaborn and Matplotlib in a data project?

In [200]:
#Aspect                   Matplotlib                          Seaborn
#Level                    Low-level (basic)                   High-level (advanced)
#Complexity               More code needed                    Less code needed
#Default Style            Basic/plain                         Beautiful/professional
#Built on                 Standalone                          Built on Matplotlib
#Best for                 Customization                       Quick visualization
#Learning                 Curve                               SteepGentle


#Use Matplotlib when :
# Need complete customization
# Creating complex, publication-ready plots
# Building animated visualizations
# Creating subplots with specific layouts
# Working with non-tabular data (raw arrays)
# Need pixel-level control

#Use Seaborn when:
# Quick exploratory data analysis
# Statistical visualizations
# Working with Pandas DataFrames
# Want beautiful plots with minimal code
# Analyzing distributions and relationships
# Creating professional-looking visuals quickly

### 9.	When should you use .loc[] and when .iloc[]?

In [214]:
# Common Use Cases
# Use .loc[] when:
# ✓ You know the row/column label or name
# ✓ Working with custom index (strings, dates, etc.)
# ✓ Using boolean conditions
# ✓ The data has meaningful labels

df = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-02', '2024-01-03'],
    'Sales': [100, 150, 200]
}, index=pd.to_datetime(['2024-01-01', '2024-01-02', '2024-01-03']))

print(df)

# .loc[] with date label
print(df.loc['2024-01-02'])

# .iloc[] with position
print(df.iloc[1])

# Examples:
print(df.loc['2024-01-01', 'Sales'])           # Date index

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 28, 35],
    'Score': [85, 90, 88, 92]
})


print(df.loc[df['Age'] > 25])                  # Boolean condition
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 28, 35],
    'Score': [85, 90, 88, 92]
})

# Set 'Name' as index
df = df.set_index('Name')
print(df)
# Get multiple people
print(df.loc[['Alice', 'Charlie'], ['Age', 'Score']])

#another way
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 28, 35],
    'Score': [85, 90, 88, 92]
})

# Use boolean condition to find 'Alice'
print(df.loc[df['Name'] == 'Alice', ['Age', 'Score']])


# Get multiple people
print(df.loc[df['Name'].isin(['Alice', 'Charlie']), ['Age', 'Score']])

                  Date  Sales
2024-01-01  2024-01-01    100
2024-01-02  2024-01-02    150
2024-01-03  2024-01-03    200
Date     2024-01-02
Sales           150
Name: 2024-01-02 00:00:00, dtype: object
Date     2024-01-02
Sales           150
Name: 2024-01-02 00:00:00, dtype: object
100
      Name  Age  Score
1      Bob   30     90
2  Charlie   28     88
3    David   35     92
         Age  Score
Name
Alice     25     85
Bob       30     90
Charlie   28     88
David     35     92
         Age  Score
Name
Alice     25     85
Charlie   28     88
   Age  Score
0   25     85
   Age  Score
0   25     85
2   28     88

### 10.	What is the importance of writing functions in Python?

In [215]:
# Functions are essential for writing professional Python code because they:

# Eliminate repetition - Write once, use many times
# Improve organization - Structure your code logically
# Ease maintenance - Update in one place, affects everywhere
# Enable testing - Test individual components
# Enhance readability - Self-documenting code 
# Promote reusability - Share across projects
# Simplify debugging - Isolate problems easier
# Facilitate collaboration - Clear interfaces for teamwork

# Without functions: Code becomes messy, hard to maintain, and error-prone 
# With functions: Code is clean, professional, and scalable 
# Functions are a fundamental building block of good programming!

## Task 3b
### Scripting-Based Questions

#### 1.	Write a program to take a name and age from the user and print a greeting message.

In [216]:
def greet_user(name, age):    
    print(f"Hello {name}! You are {age} years old.")

name = input("Enter your name: ")
age = input("Enter your age: ")

greet_user(name, age)

Enter your name:  Nanda Kumar Govindan
Enter your age:  45

Hello Nanda Kumar Govindan! You are 45 years old.

#### 2.	Create a list of numbers and print only even numbers using a for loop.

In [217]:
# Create a list of numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Print only even numbers using for loop
print("Even numbers:")
for num in numbers:
    if num % 2 == 0:  # Check if number is divisible by 2
        print(num, end=' ')  # Print on same line with space

print()  # New line at the end

Even numbers:
2 4 6 8 10

#### 3.	Write a program that handles division by zero using try-except.

In [219]:
def divide_numbers(a, b):
    try:
        result = a / b
        return result
    
    except ZeroDivisionError:
        print("Error: Cannot divide by zero!")
        return None
    
    except TypeError:
        print("Error: Both inputs must be numbers!")
        return None

# Test the function
print("Division 1:")
result1 = divide_numbers(10, 2)
if result1 is not None:
    print(f"Result: {result1}")

print("\nDivision 2:")
result2 = divide_numbers(10, 0)

print("\nDivision 3:")
result3 = divide_numbers(10, "abc")

Division 1:
Result: 5.0

Division 2:
Error: Cannot divide by zero!

Division 3:
Error: Both inputs must be numbers!

### 4.	Given a string, count how many vowels it has

In [7]:
input_string = input("Type any text here : ").lower()
vowels_list = ['a','e','i','o','u']
vowels_count = 0

for i in range(0,len(input_string)):
    if input_string[i] in vowels_list:
        vowels_count = vowels_count+1

print("Total number of vowels in the input string is : ",vowels_count)

Type any text here :  Hi Everyone, I'm Nanda Kumar Govindan

Total number of vowels in the input string is :  13

### 5.	Reverse a list without using built-in functions.

In [16]:
List_1 = ['a','e','i','o','u']
List_2 =[]
print("List_1 before reversal ", List_1)
for i in range(len(List_1),0,-1):
    List_2.append(List_1[i-1])
List_1 = List_2
print("List_1 after reversal ", List_1)

List_1 before reversal  ['a', 'e', 'i', 'o', 'u']
List_1 after reversal  ['u', 'o', 'i', 'e', 'a']

In [17]:
# Another option is
List_1 = ['a','e','i','o','u']
List_2 = []

print("List_1 before reversal ", List_1)

# directly using negative indices
for i in range(len(List_1)):
    List_2.append(List_1[-(i+1)])

List_1 = List_2
print("List_1 after reversal ", List_1)

List_1 before reversal  ['a', 'e', 'i', 'o', 'u']
List_1 after reversal  ['u', 'o', 'i', 'e', 'a']

### 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [19]:
Dict_Info = {'RollNo':430020083,
             'FirstName':'Nanda Kumar',
             'LastName':'Govindan',
             'Email':'nanda.gnk@gmail.com',
             'Age':45,
             'JobTitle':'Principle Engineer',
             'Married':True
            }
print(Dict_Info)

{'RollNo': 430020083, 'FirstName': 'Nanda Kumar', 'LastName': 'Govindan', 'Email': 'nanda.gnk@gmail.com', 'Age': 45, 'JobTitle': 'Principle Engineer', 'Married': True}

In [ ]:
7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [27]:
import pandas as pd
pd.read_csv('insurance.csv').head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [30]:
# Sort by charges - Top 5 patients
import pandas as pd
pd.read_csv('insurance.csv').sort_values('charges',ascending=False).head(5)

      age     sex     bmi  children smoker     region      charges
543    54  female  47.410         0    yes  southeast  63770.42801
1300   45    male  30.360         0    yes  southeast  62592.87309
1230   52    male  34.485         3    yes  northwest  60021.39897
577    31  female  38.095         1    yes  northeast  58571.07448
819    33  female  35.530         0    yes  northwest  55135.40209

### 8.	Create a DataFrame from a Python dictionary.

In [31]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 28, 35],
    'Score': [85, 90, 88, 92]
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   28     88
3    David   35     92

### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [41]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 32, 35],
    'Score': [85, 90, np.nan, 92]
}
df = pd.DataFrame(data)
print(df)

# Check for missing values
print("Missing values:")
print(df.isnull())
print("\n")

# Replace missing values with column mean
df['Score'] = df['Score'].fillna(df['Score'].mean())

print("After replacing NaN with column mean:")
print(df)

      Name  Age  Score
0    Alice   25   85.0
1      Bob   30   90.0
2  Charlie   32    NaN
3    David   35   92.0
Missing values:
    Name    Age  Score
0  False  False  False
1  False  False  False
2  False  False   True
3  False  False  False


After replacing NaN with column mean:
      Name  Age  Score
0    Alice   25   85.0
1      Bob   30   90.0
2  Charlie   32   89.0
3    David   35   92.0

### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30

In [44]:
df[df["Age"]>30]

      Name  Age  Score
2  Charlie   32   89.0
3    David   35   92.0

In [46]:
 df.loc[df['Age'] > 30]

      Name  Age  Score
2  Charlie   32   89.0
3    David   35   92.0

In [47]:
 df.query('Age > 30')

      Name  Age  Score
2  Charlie   32   89.0
3    David   35   92.0