## Advanced Data Anaysis

### Top 8 Powerful functions in Python for Deeper Data Analysis

1. Groupby
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. merge
7. apply
8. lambda
9. del(keyword)

#### input files referred/used in this Data Analysis, make sure these files are present in this directory

1. insurance.csv
2. Sales-Transactions-2017.csv
3. Sales-Transactions-2018.csv
4. Sales-Transactions-2017.csv
5. Sales-Transactions-Edited.csv

### 1. Groupby

In [7]:
import pandas as pd
insurance_data = pd.read_csv("insurance.csv")

In [8]:
insurance_data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [11]:
insurance_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [13]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

#### Pull up the average insurance charges based on the region

In [15]:
insurance_data["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [16]:
insurance_data["region"].nunique()

4

In [34]:
insurance_data.groupby(by="region").mean("all").round(2).sort_values(by="charges")

             age    bmi  children   charges
region
southwest  39.46  30.60      1.14  12346.94
northwest  39.20  29.20      1.15  12417.58
northeast  39.27  29.17      1.05  13406.38
southeast  38.94  33.36      1.05  14735.41

In [32]:
insurance_data.groupby(by="region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

In [36]:
insurance_data.groupby(by="region")["charges"].mean().sort_values(ascending = False).round(2)

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

In [37]:
insurance_data.groupby(by="region")["charges"].sum().sort_values(ascending = False).round(2)

region
southeast    5363689.76
northeast    4343668.58
northwest    4035712.00
southwest    4012754.65
Name: charges, dtype: float64

#### Pull up the average insurance charges based on the region and sex

In [41]:
insurance_data.groupby(by=["sex","region"])["charges"].mean().sort_index(ascending = False).round(2)

sex     region
male    southwest    13412.88
        southeast    15879.62
        northwest    12354.12
        northeast    13854.01
female  southwest    11274.41
        southeast    13499.67
        northwest    12479.87
        northeast    12953.20
Name: charges, dtype: float64

In [42]:
insurance_data.groupby(by=["region","sex"])["charges"].mean().sort_index(ascending = False).round(2)

region     sex
southwest  male      13412.88
           female    11274.41
southeast  male      15879.62
           female    13499.67
northwest  male      12354.12
           female    12479.87
northeast  male      13854.01
           female    12953.20
Name: charges, dtype: float64

In [43]:
insurance_data.groupby(by=["region","sex"])["charges"].mean().sort_values(ascending = False).round(2)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

### 2. pivot table

Discreate and Continuous data

1. Discrete - Just countable can't be segmented (example - Region, Gender, City, Eduction, Qualification, Skill, Phone number, Married, Smoker)
2. Continuous Data - Measurable, Have Units, Can also be segemented. (example - Age, Charges, BMI, Salary, Marks, Qty Purchased, Total amount)

In [48]:
# default aggregation is mean
pd.pivot_table(data = insurance_data, values="charges",index="region", columns="sex").round(2)

sex          female      male
region
northeast  12953.20  13854.01
northwest  12479.87  12354.12
southeast  13499.67  15879.62
southwest  11274.41  13412.88

In [46]:
pd.pivot_table(data = insurance_data, values="charges",index="sex", columns="region").round(2)

region  northeast  northwest  southeast  southwest
sex
female   12953.20   12479.87   13499.67   11274.41
male     13854.01   12354.12   15879.62   13412.88

In [61]:
#use the argument aggfunc to change the aggregation function
pd.pivot_table(data = insurance_data, values="charges",index="sex", columns="region",aggfunc="sum").round(2)

region   northeast   northwest   southeast   southwest
sex
female  2085465.71  2046698.75  2362442.12  1826454.62
male    2258202.88  1989013.25  3001247.65  2186300.02

In [62]:
pd.pivot_table(data = insurance_data, values="charges",index="sex", columns="region",aggfunc=["min","max"]).round(2)

             min                                     max                      \
region northeast northwest southeast southwest northeast northwest southeast
sex
female   2196.47   2117.34   1607.51   1727.78  58571.07   55135.4  63770.43
male     1694.80   1621.34   1121.87   1241.56  48549.18   60021.4  62592.87


region southwest
sex
female  48824.45
male    52590.83

In [49]:
pd.pivot_table(data = insurance_data, values="charges",index="region", columns=["sex","children"]).round(2)

sex          female                                                    \
children          0         1         2         3         4         5
region
northeast   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
northwest  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
southeast  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
southwest  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65

sex            male
children          0         1         2         3         4         5
region
northeast  13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest   9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast  13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest  13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

In [51]:
pd.pivot_table(data = insurance_data, values="charges",index=["region","sex"], columns=["children"]).round(2)

children                 0         1         2         3         4         5
region    sex
northeast female   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
          male    13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest female  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
          male     9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast female  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
          male    13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest female  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65
          male    13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

### 3 generating Aggregates in single step

In [56]:
insurance_data.groupby(by="region")["charges"].agg(["count","min","max","sum","mean"]).round(2)

           count      min       max         sum      mean
region
northeast    324  1694.80  58571.07  4343668.58  13406.38
northwest    325  1621.34  60021.40  4035712.00  12417.58
southeast    364  1121.87  63770.43  5363689.76  14735.41
southwest    325  1241.56  52590.83  4012754.65  12346.94

In [58]:
insurance_data.groupby(by=["region","sex"])["charges"].agg(["count","min","max","sum","mean"]).round(2)

                  count      min       max         sum      mean
region    sex
northeast female    161  2196.47  58571.07  2085465.71  12953.20
          male      163  1694.80  48549.18  2258202.88  13854.01
northwest female    164  2117.34  55135.40  2046698.75  12479.87
          male      161  1621.34  60021.40  1989013.25  12354.12
southeast female    175  1607.51  63770.43  2362442.12  13499.67
          male      189  1121.87  62592.87  3001247.65  15879.62
southwest female    162  1727.78  48824.45  1826454.62  11274.41
          male      163  1241.56  52590.83  2186300.02  13412.88

In [59]:
insurance_data.groupby(by=["region","sex"])["charges"].aggregate(["count","min","max","sum","mean"]).round(2)

                  count      min       max         sum      mean
region    sex
northeast female    161  2196.47  58571.07  2085465.71  12953.20
          male      163  1694.80  48549.18  2258202.88  13854.01
northwest female    164  2117.34  55135.40  2046698.75  12479.87
          male      161  1621.34  60021.40  1989013.25  12354.12
southeast female    175  1607.51  63770.43  2362442.12  13499.67
          male      189  1121.87  62592.87  3001247.65  15879.62
southwest female    162  1727.78  48824.45  1826454.62  11274.41
          male      163  1241.56  52590.83  2186300.02  13412.88

### 4 Cross Tab

A crosstab (cross-tabulation) is a table that shows the frequency distribution of variables. It's used to analyze the relationship between two or more categorical variables.

#### How many Smokers and Non-smokers based on region?

In [64]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [91]:
pd.crosstab(index = insurance_data["region"],
    columns = insurance_data["smoker"]
   )

smoker      no  yes
region
northeast  257   67
northwest  267   58
southeast  273   91
southwest  267   58

In [76]:
pd.crosstab(index = insurance_data["region"],
    columns = insurance_data["smoker"],
    margins = True
   )

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [77]:
pd.crosstab(index = insurance_data["sex"],
    columns = insurance_data["smoker"],
    margins = True
   )

smoker    no  yes   All
sex
female   547  115   662
male     517  159   676
All     1064  274  1338

In [78]:
import pandas as pd

# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Alice', 'Bob'],
    'Product': ['A', 'B', 'A', 'B', 'B', 'A'],
    'Status': ['Bought', 'Bought', 'Not Bought', 'Bought', 'Bought', 'Not Bought']
}
df = pd.DataFrame(data)

print("Original Data:")
print(df)
print("\n")

# Create a crosstab
crosstab_result = pd.crosstab(df['Product'], df['Status'])

print("Crosstab (Product vs Status):")
print(crosstab_result)

Original Data:
      Name Product      Status
0    Alice       A      Bought
1      Bob       B      Bought
2  Charlie       A  Not Bought
3    David       B      Bought
4    Alice       B      Bought
5      Bob       A  Not Bought


Crosstab (Product vs Status):
Status   Bought  Not Bought
Product
A             1           2
B             3           0

In [80]:
# Syntax
# pd.crosstab(index, columns, values=None, aggfunc=None, margins=False)

# index: Column for rows
# columns: Column for columns
# values: Column to aggregate (optional)
# aggfunc: Aggregation function (sum, mean, count, etc.)
# margins: Show row/column totals

In [81]:
import pandas as pd

data = {
    'Gender': ['M', 'F', 'M', 'F', 'M', 'F'],
    'City': ['NYC', 'LA', 'NYC', 'LA', 'NYC', 'NYC']
}
df = pd.DataFrame(data)

print("Original Data:")
print(df)
print("\n")

# Create crosstab
result = pd.crosstab(df['Gender'], df['City'])

print("Crosstab (Gender vs City):")
print(result)

Original Data:
  Gender City
0      M  NYC
1      F   LA
2      M  NYC
3      F   LA
4      M  NYC
5      F  NYC


Crosstab (Gender vs City):
City    LA  NYC
Gender
F        2    1
M        0    3

In [82]:
import pandas as pd

data = {
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Region': ['North', 'North', 'South', 'South', 'North', 'South'],
    'Sales': [100, 150, 200, 180, 120, 160]
}
df = pd.DataFrame(data)

print("Original Data:")
print(df)
print("\n")

# Crosstab with sum aggregation
result = pd.crosstab(df['Product'], df['Region'], values=df['Sales'], aggfunc='sum')

print("Crosstab (Product vs Region, Sum of Sales):")
print(result)

Original Data:
  Product Region  Sales
0       A  North    100
1       B  North    150
2       A  South    200
3       B  South    180
4       A  North    120
5       B  South    160


Crosstab (Product vs Region, Sum of Sales):
Region   North  South
Product
A          220    200
B          150    340

In [87]:
# The above result using pivot

sales_data = {
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Region': ['North', 'North', 'South', 'South', 'North', 'South'],
    'Sales': [100, 150, 200, 180, 120, 160]
}
df_sales_data = pd.DataFrame(sales_data)
pd.pivot_table(data = df_sales_data, values="Sales",index="Product", columns="Region",aggfunc="sum").round(2)

Region   North  South
Product
A          220    200
B          150    340

In [93]:
pd.pivot_table(data = insurance_data, values="charges",index="region", columns="sex",aggfunc="count").round(2)

sex        female  male
region
northeast     161   163
northwest     164   161
southeast     175   189
southwest     162   163

In [98]:
df = pd.DataFrame(insurance_data)
pd.crosstab(df['region'], df['sex'])

sex        female  male
region
northeast     161   163
northwest     164   161
southeast     175   189
southwest     162   163

In [102]:
df = pd.DataFrame(insurance_data)
pd.crosstab(df['region'], df['smoker'])

smoker      no  yes
region
northeast  257   67
northwest  267   58
southeast  273   91
southwest  267   58

In [108]:
# Use CROSSTAB when:
# - You just want counts of categorical variables
# - You want simple, quick analysis
# - You're doing a frequency distribution
# - You need quick categorical relationship analysis

# pd.crosstab(df['Gender'], df['Product'])

# Use PIVOT TABLE when:
# - You need to aggregate values (not just count)
# - You need multiple aggregation functions
# - You need to aggregate multiple columns
# - You need more flexibility and control
# - You're doing complex data reshaping

# df.pivot_table(values=['Sales', 'Profit'],
               #index='Product',
               #columns='Region',
               #aggfunc=['sum', 'mean', 'count'],
               #margins=True)

In [109]:
import pandas as pd

# CROSSTAB - Simple, focused
# For: Quick categorical analysis, counting
# pd.crosstab(df['col1'], df['col2'])
# pd.crosstab(df['col1'], df['col2'], values=df['col3'], aggfunc='sum', margins=True)

# PIVOT TABLE - Flexible, powerful
# For: Complex aggregations, reshaping
# df.pivot_table(values='col3', index='col1', columns='col2', aggfunc='sum')
# df.pivot_table(values=['col3', 'col4'], index='col1', columns='col2', 
               # aggfunc=['sum', 'mean', 'count'], margins=True)

### Concat

In [111]:
sales_data_2017 = pd.read_csv('Sales-Transactions-2017.csv')
sales_data_2018 = pd.read_csv('Sales-Transactions-2018.csv')
sales_data_2019 = pd.read_csv('Sales-Transactions-2019.csv')

In [170]:
# pd.concat will perform union all on operation on dataframes
# important think to note is that all the dataframes should have the same no of columns
sales_data_combined = pd.concat(objs=[sales_data_2017,sales_data_2018,sales_data_2019])
sales_data_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### Task 1 - Data Cleaning Challenge on Sales Data.
The following set of actions performed on the sales_data_combined generated as part of the previous step.

1. Analyse the data for null values
2. Verify the data types of sales_data_combined
3. Describe the data
4. find the shape
5. Removing duplicate rows
6. Removing the columns contain more null values ("Disc" and "Voucher Amount") based on the inferences
7. Reemoving rows missing values
8. Converting the data types from objects to date and time, integer and float when possible.

In [171]:
sales_data_combined.isna()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...
19171,False,False,False,False,False,False,False,True,True
19172,True,True,True,True,True,True,True,True,True
19173,True,True,True,True,True,True,True,True,True
19174,True,False,True,True,False,False,False,False,False
19175,True,False,True,True,False,False,False,False,False

In [127]:
sales_data_combined.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [172]:
sales_data_combined.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [173]:
sales_data_combined.shape

(111206, 9)

In [138]:
sales_data_combined.describe()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

#### Cleaning Data

In [174]:
sales_data_combined = sales_data_combined.drop_duplicates()   # Remove duplicates

In [175]:
sales_data_combined.shape

(96624, 9)

In [123]:
sales_data_combined.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN

In [129]:
# alternate method to remove duplicates in this methond no need to assign the result to another df
# this one directly remove the duplicates from DF
sales_data_combined.drop_duplicates(inplace = True)

In [131]:
sales_data_combined.shape

(96624, 9)

In [141]:
sales_data_combined.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [168]:
sales_data_combined.shape

(1374, 9)

In [135]:
sales_data_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
6,1/4/2017,Sal:898,Lock,Vishnu 250ml,100,30,"3,000.00",100,"5,400.00"
8,,,khader vali late en,,,,,,
9,,,try,,,,,,
12,,,DUMMY ENTRY,,,,,,
15,,,dummy entry,,,,,,
...,...,...,...,...,...,...,...,...,...
18622,,,markfed -adurupalli,,,,,,
18899,9/10/2019,Sal:4855,JAGADHAMBA PLASTICS,LITE FOAM(1200),3,"1,680.00","5,040.00",150,"4,890.00"
19052,,,8/10 late entry,,,,,,
19057,,,10-Jul,,,,,,
19135,10/10/2019,Sal:4925,SLST-GDR,500ML PLASTIC BOULS,"1,000.00",3.55,"3,550.00","3,550.00","4,090.00"

In [229]:
#The columns "Disc" and "Voucher Amount" are having more null or NaN values hence its good to remove those columns from the analysis
#This section will work only one time as the columns get removed at the first instance this will produce error if it is run for the second time.
sales_data_combined=sales_data_combined.drop(["Disc","Voucher Amount"], axis = 1)

KeyError: "['Disc', 'Voucher Amount'] not found in axis"

In [179]:
sales_data_combined.shape

(96419, 7)

In [152]:
sales_data_combined.isna().sum()

Date       204
Voucher    170
Party       35
Product    204
Qty        170
Rate       171
Gross      171
dtype: int64

In [153]:
sales_data_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"
...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00"
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00"
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00"
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40"

### remove missing values

In [180]:
### remove the rows with NaN values
sales_data_combined = sales_data_combined.dropna()            # Remove rows with NaN

In [181]:
sales_data_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"
...,...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00"
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00"
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00"
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00"
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00"

In [156]:
sales_data_combined.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
Gross      object
dtype: object

In [183]:
# Convert to QTY column from object type to integer
sales_data_combined[sales_data_combined['Qty'] == " "]

      Date Voucher                Party Product Qty Rate Gross
8                   khader vali late en
9                                   try
12                          DUMMY ENTRY
15                          dummy entry
96                               AUTOLO
...    ...     ...                  ...     ...  ..  ...   ...
18400                 suresh adurupalli
18585                           V.S.BAR
18622               markfed -adurupalli
19052                   8/10 late entry
19057                            10-Jul

[1131 rows x 7 columns]

In [185]:
# See how many rows have empty Qty
print(f"Rows with Qty == ' ': {(sales_data_combined['Qty'] == ' ').sum()}")
print(f"Rows with empty Qty: {(sales_data_combined['Qty'].astype(str).str.strip() == '').sum()}")
print(f"Rows with NaN Qty: {sales_data_combined['Qty'].isnull().sum()}")

# Show some examples
print("\nSample rows with empty Qty:")
print(sales_data_combined[sales_data_combined['Qty'].astype(str).str.strip() == ''][['Date', 'Party', 'Product', 'Qty']].head(10))

Rows with Qty == ' ': 1131
Rows with empty Qty: 1131
Rows with NaN Qty: 0

Sample rows with empty Qty:
    Date                Party Product Qty
8         khader vali late en
9                         try
12                DUMMY ENTRY
15                dummy entry
96                     AUTOLO
102             RAJASURESH KI
122               CREDIT BILL
134                    autolo
147        sriram srinivasulu
149                late entry

In [186]:
print(f"Before: {len(sales_data_combined)} rows")

# Remove rows where Qty is empty/space
sales_data_combined = sales_data_combined[sales_data_combined['Qty'].astype(str).str.strip() != ""]

print(f"After: {len(sales_data_combined)} rows")

Before: 96419 rows
After: 95288 rows

In [187]:
#Convert the date

sales_data_combined['Date'] = pd.to_datetime(sales_data_combined['Date'], format='%m/%d/%Y', errors='coerce')

# Remove rows with invalid dates
# sales_data_combined = sales_data_combined[sales_data_combined['Date'].notna()]

print(f"Date range: {sales_data_combined['Date'].min().date()} to {sales_data_combined['Date'].max().date()}")
print(f"Rows after date conversion: {len(sales_data_combined)}")

Date range: 2017-01-04 to 2019-12-09
Rows after date conversion: 37413

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_9052\1310611227.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_data_combined['Date'] = pd.to_datetime(sales_data_combined['Date'], format='%m/%d/%Y', errors='coerce')

In [189]:
sales_data_combined.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
Gross      0
dtype: int64

In [190]:
sales_data_combined.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty                object
Rate               object
Gross              object
dtype: object

In [195]:
# Convert Qty to integer
sales_data_combined['Qty'] = pd.to_numeric(sales_data_combined['Qty'], errors='coerce').fillna(0).astype(int)

In [192]:
sales_data_combined.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty                 int64
Rate               object
Gross              object
dtype: object

In [196]:
# Convert rate to float
sales_data_combined['Rate'] = pd.to_numeric(sales_data_combined['Rate'], errors='coerce').fillna(0).astype(float)

In [197]:
sales_data_combined.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty                 int64
Rate              float64
Gross              object
dtype: object

In [198]:
# Convert Gross to float
sales_data_combined['Gross'] = pd.to_numeric(sales_data_combined['Gross'], errors='coerce').fillna(0).astype(float)

In [199]:
sales_data_combined.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty                 int64
Rate              float64
Gross             float64
dtype: object

In [200]:
sales_data_combined

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,0.0,0.0
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,0.0,0.0
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,0.0
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,0.0,0.0
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,0.0,0.0
...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,0.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,0.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,0.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,0.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,0.0

### 7 apply
Adding new columns/fields to the Dataframe

In [202]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [205]:
# Add a new column Eligibility_Criteria and it should show elegible when Age > 25 else not eligible
insurance_data['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [206]:
insurance_data.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [207]:
insurance_data.age > 25

0       False
1       False
2        True
3        True
4        True
        ...
1333     True
1334    False
1335    False
1336    False
1337     True
Name: age, Length: 1338, dtype: bool

In [208]:
insurance_data[insurance_data.age > 25]

      age     sex     bmi  children smoker     region      charges
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
...   ...     ...     ...       ...    ...        ...          ...
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1337   61  female  29.070         0    yes  northwest  29141.36030

[1032 rows x 7 columns]

In [209]:
def check_eligible_criteria(x):
    if (x > 25):
        return 'Eligible'
    else:
        return 'Not Eligible'

In [211]:
insurance_data.age.apply(check_eligible_criteria)

0       Not Eligible
1       Not Eligible
2           Eligible
3           Eligible
4           Eligible
            ...
1333        Eligible
1334    Not Eligible
1335    Not Eligible
1336    Not Eligible
1337        Eligible
Name: age, Length: 1338, dtype: object

In [213]:
insurance_data["Eligibility Criteria"]=insurance_data.age.apply(check_eligible_criteria)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Not Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [215]:
insurance_data["charges"]=insurance_data.charges.round(2)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46,Eligible
3,33,male,22.705,0,no,northwest,21984.47,Eligible
4,32,male,28.880,0,no,northwest,3866.86,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible

### 8 Lambda

Anonymous or nameless function

In [217]:
insurance_data["Eligibility Criteria 2"]=insurance_data.age.apply(lambda x:1 if x > 25 else 0)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria 2
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible,0
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible,0
2,28,male,33.000,3,no,southeast,4449.46,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47,Eligible,1
4,32,male,28.880,0,no,northwest,3866.86,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible,0
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible,0
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible,0
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible,1

In [218]:
insurance_data["EC"]=insurance_data.age.apply(lambda x:"Yes" if x > 25 else "No")
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria 2,EC
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible,0,No
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible,0,No
2,28,male,33.000,3,no,southeast,4449.46,Eligible,1,Yes
3,33,male,22.705,0,no,northwest,21984.47,Eligible,1,Yes
4,32,male,28.880,0,no,northwest,3866.86,Eligible,1,Yes
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible,1,Yes
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible,0,No
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible,0,No
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible,0,No
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible,1,Yes

In [222]:
# Eligible discount only when age < 50 and non-smoker
# method 1 using Column Names (RECOMMENDED) and axis
insurance_data["EC_Discount"] = insurance_data.apply(
    lambda row: "Yes" if (row['age'] < 50 and row['smoker'].upper() == 'YES') else "No",
    axis=1
)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria 2,EC,EC_Discount
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible,0,No,Yes
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible,0,No,No
2,28,male,33.000,3,no,southeast,4449.46,Eligible,1,Yes,No
3,33,male,22.705,0,no,northwest,21984.47,Eligible,1,Yes,No
4,32,male,28.880,0,no,northwest,3866.86,Eligible,1,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible,1,Yes,No
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible,0,No,No
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible,0,No,No
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible,0,No,No
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible,1,Yes,No

In [224]:
# Eligible discount only when age < 50 and non-smoker
# method 2 using Column index and axis(row)
insurance_data["EC_Discount"] = insurance_data[["age", "smoker"]].apply(
    lambda x: "Yes" if (x[0] < 50 and x[1].upper() == '1') else '0',
    axis=1
)
insurance_data

C:\Users\Windows 10\AppData\Local\Temp\ipykernel_9052\3297307076.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lambda x: "Yes" if (x[0] < 50 and x[1].upper() == '1') else '0',

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria 2,EC,EC_Discount
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible,0,No,0
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible,0,No,0
2,28,male,33.000,3,no,southeast,4449.46,Eligible,1,Yes,0
3,33,male,22.705,0,no,northwest,21984.47,Eligible,1,Yes,0
4,32,male,28.880,0,no,northwest,3866.86,Eligible,1,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible,1,Yes,0
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible,0,No,0
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible,0,No,0
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible,0,No,0
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible,1,Yes,0

In [225]:
# Eligible discount only when age < 50 and non-smoker
# method 3 using Unpack the Columns (Use x and y)
insurance_data["EC_Discount"] = insurance_data[["age", "smoker"]].apply(
    lambda row: "Yes" if (row['age'] < 50 and row['smoker'].upper() == 'YES') else "No",
    axis=1
)

insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria 2,EC,EC_Discount
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible,0,No,Yes
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible,0,No,No
2,28,male,33.000,3,no,southeast,4449.46,Eligible,1,Yes,No
3,33,male,22.705,0,no,northwest,21984.47,Eligible,1,Yes,No
4,32,male,28.880,0,no,northwest,3866.86,Eligible,1,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible,1,Yes,No
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible,0,No,No
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible,0,No,No
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible,0,No,No
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible,1,Yes,No

### DEL and Drop 
1. del to remove single column
2. drop to remove multiple columns
To remove the columns

In [226]:
# syntax del df["column name"]
del insurance_data["Eligibility Criteria 2"]
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,EC,EC_Discount
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible,No,Yes
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible,No,No
2,28,male,33.000,3,no,southeast,4449.46,Eligible,Yes,No
3,33,male,22.705,0,no,northwest,21984.47,Eligible,Yes,No
4,32,male,28.880,0,no,northwest,3866.86,Eligible,Yes,No
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible,Yes,No
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible,No,No
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible,No,No
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible,No,No
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible,Yes,No

In [228]:
# deleting multiple columns use drop function
insurance_data = insurance_data.drop(columns=["EC", "EC_Discount"]) 
# or
# insurance_data.drop(columns=["EC", "EC_Discount"], inplace = True) #with this approach there is no need to reassign
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46,Eligible
3,33,male,22.705,0,no,northwest,21984.47,Eligible
4,32,male,28.880,0,no,northwest,3866.86,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.55,Eligible
1334,18,female,31.920,0,no,northeast,2205.98,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94,Not Eligible
1337,61,female,29.070,0,yes,northwest,29141.36,Eligible

### Task 2 - Merge Function 1 Example
Merge combines two DataFrames by matching rows based on a common column (like a JOIN in SQL). 
Syntax : merged_df = df1.merge(df2, on='common_column'). default is inner

Same as SQL joins merge also have the following types
1. inner - same as inner join in SQL. Syntax : df1.merge(df2, on='column', how='inner') 
2. left - same as left join in SQL. Syntax : df1.merge(df2, on='column', how='left')
3. right - same as right join in SQL. Syntax : df1.merge(df2, on='column', how='right')
4. outer - same as full outer join in SQL. Syntax : df1.merge(df2, on='column', how='outer')
5. when the column names are different then merged = df1.merge(df2, left_on='col1', right_on='col2')
6. when multiple columns are used for join merged = df1.merge(df2, on=['col1', 'col2']) or when column names are not same then df1.merge(df2, left_on=['ID1', 'date1'], right_on=['ID2', 'date2'])

In [235]:
# Example 

# Dataset 1: Customer info
df_customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4,5],
    'age': [25, 30, 35, 40, 38],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Scott']
})

# Dataset 2: Insurance claims
df_claims = pd.DataFrame({
    'customer_id': [1, 2, 1, 3,6,7],
    'claim_amount': [1000, 2000, 1500, 3000,4500,2500]
})

# example for merge 

df_basic_merge = df_customers.merge(df_claims, on="customer_id")
df_basic_merge

   customer_id  age     name  claim_amount
0            1   25    Alice          1000
1            1   25    Alice          1500
2            2   30      Bob          2000
3            3   35  Charlie          3000

In [236]:
df_inner_merge = df_customers.merge(df_claims, on="customer_id", how = "inner")
df_inner_merge

   customer_id  age     name  claim_amount
0            1   25    Alice          1000
1            1   25    Alice          1500
2            2   30      Bob          2000
3            3   35  Charlie          3000

In [238]:
df_left_merge = df_customers.merge(df_claims, on="customer_id", how = "left")
df_left_merge

   customer_id  age     name  claim_amount
0            1   25    Alice        1000.0
1            1   25    Alice        1500.0
2            2   30      Bob        2000.0
3            3   35  Charlie        3000.0
4            4   40    David           NaN
5            5   38    Scott           NaN

In [239]:
df_right_merge = df_customers.merge(df_claims, on="customer_id", how = "right")
df_right_merge

   customer_id   age     name  claim_amount
0            1  25.0    Alice          1000
1            2  30.0      Bob          2000
2            1  25.0    Alice          1500
3            3  35.0  Charlie          3000
4            6   NaN      NaN          4500
5            7   NaN      NaN          2500

In [240]:
df_outer_merge = df_customers.merge(df_claims, on="customer_id", how = "outer")
df_outer_merge

   customer_id   age     name  claim_amount
0            1  25.0    Alice        1000.0
1            1  25.0    Alice        1500.0
2            2  30.0      Bob        2000.0
3            3  35.0  Charlie        3000.0
4            4  40.0    David           NaN
5            5  38.0    Scott           NaN
6            6   NaN      NaN        4500.0
7            7   NaN      NaN        2500.0

### Task 3 - List Comprehension 2 examples

List Comprehension is a quick, clean way to create a new list by applying a condition or transformation to each item in an existing list.
It's like a shortcut for writing loops in one line.

In [242]:
# Basic Syntax
# Traditional way (loop)
# new_list = []
# for item in old_list:
    # new_list.append(item * 2)

# List comprehension (one line)
# new_list = [item * 2 for item in old_list]

In [243]:
# Without List Comprehension (Traditional Loop)
numbers = [1, 2, 3, 4, 5]

# Using a loop
doubled = []
for num in numbers:
    doubled.append(num * 2)

print(doubled)  # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

In [244]:
# With List Comprehension
numbers = [1, 2, 3, 4, 5]

# One line!
doubled = [num * 2 for num in numbers]

print(doubled)  # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

In [245]:
# List Comprehension with Conditions
# Filter Even Numbers Only

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Traditional way
even = []
for num in numbers:
    if num % 2 == 0:
        even.append(num)

print(even)  # [2, 4, 6, 8, 10]

# List comprehension
even = [num for num in numbers if num % 2 == 0]

print(even)  # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]

In [246]:
# List Comprehension with If-Else
# Example: Label Numbers
numbers = [1, 2, 3, 4, 5]

# Traditional way
labels = []
for num in numbers:
    if num > 3:
        labels.append("Big")
    else:
        labels.append("Small")

print(labels)  # ['Small', 'Small', 'Small', 'Big', 'Big']

# List comprehension
labels = ["Big" if num > 3 else "Small" for num in numbers]

print(labels)  # ['Small', 'Small', 'Small', 'Big', 'Big']

['Small', 'Small', 'Small', 'Big', 'Big']
['Small', 'Small', 'Small', 'Big', 'Big']

In [247]:
# List Comprehension in Pandas
# Example 1: Create New Column Based on Condition
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'age': [25, 30, 35, 40, 45],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
})

print("Original DataFrame:")
print(df)

# Add a new column using list comprehension
df['age_group'] = ["Young" if age < 35 else "Old" for age in df['age']]

print("\nDataFrame with new column:")
print(df)

Original DataFrame:
   age     name
0   25    Alice
1   30      Bob
2   35  Charlie
3   40    David
4   45      Eve

DataFrame with new column:
   age     name age_group
0   25    Alice     Young
1   30      Bob     Young
2   35  Charlie       Old
3   40    David       Old
4   45      Eve       Old

In [248]:
# Example 2: Transform Existing Column
import pandas as pd

df = pd.DataFrame({
    'price': [100, 200, 300, 400, 500]
})

print("Original:")
print(df)

# Apply 20% discount using list comprehension
df['discounted_price'] = [price * 0.8 for price in df['price']]

print("\nWith discount:")
print(df)

Original:
   price
0    100
1    200
2    300
3    400
4    500

With discount:
   price  discounted_price
0    100              80.0
1    200             160.0
2    300             240.0
3    400             320.0
4    500             400.0

In [249]:
# Example 3: Convert Text to Uppercase
import pandas as pd

df = pd.DataFrame({
    'name': ['alice', 'bob', 'charlie'],
    'city': ['new york', 'los angeles', 'chicago']
})

print("Original:")
print(df)

# Convert to uppercase using list comprehension
df['name_upper'] = [name.upper() for name in df['name']]
df['city_upper'] = [city.upper() for city in df['city']]

print("\nWith uppercase:")
print(df)

Original:
      name         city
0    alice     new york
1      bob  los angeles
2  charlie      chicago

With uppercase:
      name         city name_upper   city_upper
0    alice     new york      ALICE     NEW YORK
1      bob  los angeles        BOB  LOS ANGELES
2  charlie      chicago    CHARLIE      CHICAGO

In [250]:
import pandas as pd

# Insurance DataFrame
insurance = pd.DataFrame({
    'age': [25, 45, 35, 55, 30],
    'smoker': ['NO', 'YES', 'NO', 'YES', 'NO'],
    'charges': [1000, 3000, 1500, 4000, 1200]
})

print("Original:")
print(insurance)

# Add risk category using list comprehension
insurance['risk_level'] = [
    "High Risk" if (age > 40 and smoker == 'YES') else "Low Risk" 
    for age, smoker in zip(insurance['age'], insurance['smoker'])
]

print("\nWith risk level:")
print(insurance)

Original:
   age smoker  charges
0   25     NO     1000
1   45    YES     3000
2   35     NO     1500
3   55    YES     4000
4   30     NO     1200

With risk level:
   age smoker  charges risk_level
0   25     NO     1000   Low Risk
1   45    YES     3000  High Risk
2   35     NO     1500   Low Risk
3   55    YES     4000  High Risk
4   30     NO     1200   Low Risk

In [251]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Keep numbers that are even AND greater than 5
filtered = [num for num in numbers if num % 2 == 0 and num > 5]

print(filtered)  # [6, 8, 10]

[6, 8, 10]

In [252]:
# Create a 2D list
matrix = [[num * row for num in range(1, 4)] for row in range(1, 4)]

print(matrix)
# [[1, 2, 3], [2, 4, 6], [3, 6, 9]]

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]

In [253]:
people = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 35},
    {'name': 'Charlie', 'age': 30},
    {'name': 'David', 'age': 40}
]

names_over_30 = []
for person in people:
    if person['age'] > 30:
        names_over_30.append(person['name'])

print(names_over_30)  # ['Bob', 'David']

['Bob', 'David']

In [254]:
people = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 35},
    {'name': 'Charlie', 'age': 30},
    {'name': 'David', 'age': 40}
]

names_over_30 = [person['name'] for person in people if person['age'] > 30]

print(names_over_30)  # ['Bob', 'David']

['Bob', 'David']

In [255]:
import pandas as pd

# Customer data
df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['alice', 'bob', 'charlie', 'david', 'eve'],
    'purchase_amount': [100, 50, 200, 75, 150]
})

# Add multiple new columns using list comprehension

# 1. Uppercase name
df['name_upper'] = [name.upper() for name in df['name']]

# 2. Discount (10% for purchases > 100)
df['discount'] = [amount * 0.1 if amount > 100 else 0 for amount in df['purchase_amount']]

# 3. Customer type
df['customer_type'] = ["VIP" if amount > 150 else "Regular" for amount in df['purchase_amount']]

# 4. Final amount after discount
df['final_amount'] = [amount - discount for amount, discount in zip(df['purchase_amount'], df['discount'])]

print(df)

   customer_id     name  purchase_amount name_upper  discount customer_type  \
0            1    alice              100      ALICE       0.0       Regular
1            2      bob               50        BOB       0.0       Regular
2            3  charlie              200    CHARLIE      20.0           VIP
3            4    david               75      DAVID       0.0       Regular
4            5      eve              150        EVE      15.0       Regular

   final_amount
0         100.0
1          50.0
2         180.0
3          75.0
4         135.0

### Task 4 - Lambda Function 2 examples with Map, Filter, Reduce
1. MAP
2. Filter
3. Reduce

#### MAP - Apply Function to Each Item
#### Simple Definition - Map applies a function to every item in a list and returns a new list.

In [275]:
# Example 1: Double All Numbers
numbers = [1, 2, 3, 4, 5]

# Using regular function
def double(x):
    return x * 2

doubled = list(map(double, numbers))
print(doubled)  # [2, 4, 6, 8, 10]

# Using lambda (cleaner!)
doubled = list(map(lambda x: x * 2, numbers))
print(doubled)  # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]

In [257]:
# Example 2: Convert Temperature F to C

fahrenheit = [32, 68, 86, 104]

# Without lambda
def f_to_c(f):
    return (f - 32) * 5/9

celsius = list(map(f_to_c, fahrenheit))
print(celsius)  # [0.0, 20.0, 30.0, 40.0]

# With lambda (one line!)
celsius = list(map(lambda f: (f - 32) * 5/9, fahrenheit))
print(celsius)  # [0.0, 20.0, 30.0, 40.0]

[0.0, 20.0, 30.0, 40.0]
[0.0, 20.0, 30.0, 40.0]

In [258]:
# Example 3: Convert Strings to Uppercase
names = ['alice', 'bob', 'charlie', 'david']

# With lambda
uppercase_names = list(map(lambda name: name.upper(), names))
print(uppercase_names)  # ['ALICE', 'BOB', 'CHARLIE', 'DAVID']

['ALICE', 'BOB', 'CHARLIE', 'DAVID']

In [259]:
# Example 4: Map on Multiple Lists
list1 = [1, 2, 3]
list2 = [10, 20, 30]

# Add corresponding elements
result = list(map(lambda x, y: x + y, list1, list2))
print(result)  # [11, 22, 33]

[11, 22, 33]

In [260]:
# Map with Pandas DataFrames
import pandas as pd

df = pd.DataFrame({
    'name': ['alice', 'bob', 'charlie'],
    'salary': [50000, 60000, 75000]
})

print("Original:")
print(df)

# Apply lambda to salary column (10% raise)
df['new_salary'] = df['salary'].map(lambda x: x * 1.1)

# Apply lambda to name column (uppercase)
df['name_upper'] = df['name'].map(lambda x: x.upper())

print("\nWith transformations:")
print(df)

Original:
      name  salary
0    alice   50000
1      bob   60000
2  charlie   75000

With transformations:
      name  salary  new_salary name_upper
0    alice   50000     55000.0      ALICE
1      bob   60000     66000.0        BOB
2  charlie   75000     82500.0    CHARLIE

#### 2. FILTER - Keep Items That Match Condition
Simple Definition
Filter keeps only items that match a condition (return True).

In [261]:
# Example 1: Get Only Even Numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Without lambda
def is_even(x):
    return x % 2 == 0

even_numbers = list(filter(is_even, numbers))
print(even_numbers)  # [2, 4, 6, 8, 10]

# With lambda (cleaner!)
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)  # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]

In [262]:
# Example 2: Filter Names Longer Than 3 Characters
names = ['alice', 'bob', 'charlie', 'david', 'eve']

# With lambda
long_names = list(filter(lambda name: len(name) > 3, names))
print(long_names)  # ['alice', 'charlie', 'david']

['alice', 'charlie', 'david']

In [263]:
# Example 3: Filter Numbers Greater Than 50
scores = [45, 68, 32, 78, 55, 90, 42]

# With lambda
passing_scores = list(filter(lambda score: score > 50, scores))
print(passing_scores)  # [68, 78, 55, 90]

[68, 78, 55, 90]

In [264]:
# Example 4: Filter Complex Condition
people = [
    {'name': 'alice', 'age': 25, 'salary': 50000},
    {'name': 'bob', 'age': 35, 'salary': 60000},
    {'name': 'charlie', 'age': 28, 'salary': 75000},
    {'name': 'david', 'age': 45, 'salary': 80000}
]

# Filter: age > 30 AND salary > 60000
filtered = list(filter(lambda p: p['age'] > 30 and p['salary'] > 60000, people))
print(filtered)
# [{'name': 'bob', 'age': 35, 'salary': 60000}, {'name': 'david', 'age': 45, 'salary': 80000}]

[{'name': 'david', 'age': 45, 'salary': 80000}]

In [265]:
# Filter with Pandas DataFrames
import pandas as pd

df = pd.DataFrame({
    'age': [25, 30, 35, 40, 45],
    'income': [30000, 45000, 60000, 75000, 90000],
    'name': ['alice', 'bob', 'charlie', 'david', 'eve']
})

print("Original:")
print(df)

# Filter rows where age > 30
filtered_df = df[df['age'] > 30]

print("\nFiltered (age > 30):")
print(filtered_df)

Original:
   age  income     name
0   25   30000    alice
1   30   45000      bob
2   35   60000  charlie
3   40   75000    david
4   45   90000      eve

Filtered (age > 30):
   age  income     name
2   35   60000  charlie
3   40   75000    david
4   45   90000      eve

### 3. REDUCE - Combine All Items Into One
#### from functools import reduce

In [266]:
Example 1: Sum All Numbers
from functools import reduce

numbers = [1, 2, 3, 4, 5]

# Without lambda
def add(x, y):
    return x + y

total = reduce(add, numbers)
print(total)  # 15

# With lambda
total = reduce(lambda x, y: x + y, numbers)
print(total)  # 15

15
15

In [267]:
# Example 2: Multiply All Numbers (Factorial)
from functools import reduce

numbers = [1, 2, 3, 4, 5]

# With lambda
product = reduce(lambda x, y: x * y, numbers)
print(product)  # 120 (5! = 5*4*3*2*1)

120

In [268]:
# Example 3: Find Maximum Number
from functools import reduce

numbers = [3, 7, 2, 9, 1, 5]

# With lambda
max_num = reduce(lambda x, y: x if x > y else y, numbers)
print(max_num)  # 9

9

In [269]:
# Example 4: Concatenate Strings
from functools import reduce

words = ['hello', ' ', 'world', '!']

# With lambda
sentence = reduce(lambda x, y: x + y, words)
print(sentence)  # "hello world!"

hello world!

In [270]:
# Example 5: Find Minimum Number
from functools import reduce

numbers = [15, 3, 27, 8, 42, 1]

# With lambda
min_num = reduce(lambda x, y: x if x < y else y, numbers)
print(min_num)  # 1

1

In [271]:
# Complete Real-World Examples
# Example 1: Processing Customer Data
from functools import reduce

customers = [
    {'name': 'alice', 'purchase': 100},
    {'name': 'bob', 'purchase': 50},
    {'name': 'charlie', 'purchase': 200},
    {'name': 'david', 'purchase': 75}
]

# MAP: Add 10% discount
with_discount = list(map(lambda c: {'name': c['name'], 'amount': c['purchase'] * 0.9}, customers))
print("After discount:")
print(with_discount)

# FILTER: Keep purchases > 70
high_purchases = list(filter(lambda c: c['purchase'] > 70, customers))
print("\nHigh purchases (> 70):")
print(high_purchases)

# REDUCE: Total revenue
total = reduce(lambda x, y: x + y['purchase'], customers, 0)
print(f"\nTotal revenue: ${total}")

After discount:
[{'name': 'alice', 'amount': 90.0}, {'name': 'bob', 'amount': 45.0}, {'name': 'charlie', 'amount': 180.0}, {'name': 'david', 'amount': 67.5}]

High purchases (> 70):
[{'name': 'alice', 'purchase': 100}, {'name': 'charlie', 'purchase': 200}, {'name': 'david', 'purchase': 75}]

Total revenue: $425

In [272]:
# Example 2: Insurance Data Processing
from functools import reduce
import pandas as pd

# Insurance data
insurance = [
    {'age': 25, 'smoker': 'NO', 'charges': 1000},
    {'age': 45, 'smoker': 'YES', 'charges': 3000},
    {'age': 35, 'smoker': 'NO', 'charges': 1500},
    {'age': 55, 'smoker': 'YES', 'charges': 4000},
    {'age': 30, 'smoker': 'NO', 'charges': 1200}
]

print("Original data:")
for person in insurance:
    print(person)

# MAP: Add risk level
risk_level = list(map(
    lambda p: {**p, 'risk': 'High' if (p['age'] > 40 and p['smoker'] == 'YES') else 'Low'},
    insurance
))

print("\nWith risk level:")
for person in risk_level:
    print(person)

# FILTER: High-risk customers
high_risk = list(filter(lambda p: p['age'] > 40 and p['smoker'] == 'YES', insurance))

print("\nHigh-risk customers:")
for person in high_risk:
    print(person)

# REDUCE: Total charges
total_charges = reduce(lambda x, y: x + y['charges'], insurance, 0)
print(f"\nTotal charges: ${total_charges}")

# REDUCE: Average charges
avg_charges = total_charges / len(insurance)
print(f"Average charges: ${avg_charges:.2f}")

Original data:
{'age': 25, 'smoker': 'NO', 'charges': 1000}
{'age': 45, 'smoker': 'YES', 'charges': 3000}
{'age': 35, 'smoker': 'NO', 'charges': 1500}
{'age': 55, 'smoker': 'YES', 'charges': 4000}
{'age': 30, 'smoker': 'NO', 'charges': 1200}

With risk level:
{'age': 25, 'smoker': 'NO', 'charges': 1000, 'risk': 'Low'}
{'age': 45, 'smoker': 'YES', 'charges': 3000, 'risk': 'High'}
{'age': 35, 'smoker': 'NO', 'charges': 1500, 'risk': 'Low'}
{'age': 55, 'smoker': 'YES', 'charges': 4000, 'risk': 'High'}
{'age': 30, 'smoker': 'NO', 'charges': 1200, 'risk': 'Low'}

High-risk customers:
{'age': 45, 'smoker': 'YES', 'charges': 3000}
{'age': 55, 'smoker': 'YES', 'charges': 4000}

Total charges: $10700
Average charges: $2140.00

In [274]:
# When to Use Each
numbers = [1, 2, 3, 4, 5]

# MAP: Transform (double each)
mapped = list(map(lambda x: x * 2, numbers))
print(mapped)
# Result: [2, 4, 6, 8, 10]

# FILTER: Keep only evens
filtered = list(filter(lambda x: x % 2 == 0, numbers))
print(filtered)
# Result: [2, 4]

# REDUCE: Sum all
from functools import reduce
reduced = reduce(lambda x, y: x + y, numbers)
print(reduced)
# Result: 15

[2, 4, 6, 8, 10]
[2, 4]
15