## Python Built-in Data Structures
* To collect mulitple data in a structure

#### 4 Data structures in Python
1. List
2. Sets
3. Tuples
4. Dictionaries - key value pair

## 1. List

List accept duplicate values.
Hetrogeneous data
Key points:

Keeps insertion order ✅
You can change values ✅
Allows duplicate elements ✅

Use when:
You need a collection that can change (add/remove/update items)

In [5]:
empty_cart=[]
empty_cart

[]

In [6]:
type(empty_cart)

list

In [2]:
student_marks = [83,67,97,75,66]
student_marks

[83, 67, 97, 75, 66]

In [3]:
type(student_marks)

list

In [7]:
fruits_list = ['apple','orange','grapes','banana','mango','watermelon']
fruits_list

['apple', 'orange', 'grapes', 'banana', 'mango', 'watermelon']

In [8]:
student_rec = ['Nanda','Govindan',46,'nanda.gnk@gmail.com','0405891583']
student_rec

['Nanda', 'Govindan', 46, 'nanda.gnk@gmail.com', '0405891583']

In [10]:
len(student_rec)

5

In [11]:
student_rec[0]

'Nanda'

In [13]:
student_rec[len(student_rec)-1]

'0405891583'

In [15]:
student_rec[-1]

'0405891583'

In [16]:
student_rec[-5]

'Nanda'

In [18]:
student_rec[0:3]

['Nanda', 'Govindan', 46]

In [23]:
student_rec[2:4]

[46, 'nanda.gnk@gmail.com']

In [21]:
student_rec[5:1:-1]

['0405891583', 'nanda.gnk@gmail.com', 46]

In [59]:
student_rec[5:0:-1]

['0405891583', 'nanda.gnk@gmail.com', 46, 'Govindan']

In [31]:
student_rec[-5:-1]

['Nanda', 'Govindan', 46, 'nanda.gnk@gmail.com']

In [62]:
student_rec[-1:0:-1]

['0405891583', 'nanda.gnk@gmail.com', 46, 'Govindan']

In [63]:
# list is mutable an item value can be modified using the index
student_rec[1]='GOVINDAN'
student_rec

['Nanda', 'GOVINDAN', 46, 'nanda.gnk@gmail.com', '0405891583']

In [64]:
student_rec.pop(3)
student_rec

['Nanda', 'GOVINDAN', 46, '0405891583']

In [65]:
# append add a new item at the end of the list by default
student_rec.append('MCA')
student_rec

['Nanda', 'GOVINDAN', 46, '0405891583', 'MCA']

In [66]:
#insert add an item in the list in the index posistion
student_rec.insert(3,"nanda.gnk@gmail.com")
student_rec

['Nanda', 'GOVINDAN', 46, 'nanda.gnk@gmail.com', '0405891583', 'MCA']

## Sets
used to perform set operations like union, intersection, union all, minus 

1. one dimentional
2. Hetrogeneous
3. won't allow duplicate values
4. individual items are not accessble using index.
5. sort the items by default

In [70]:
empty_set = set()
empty_set

set()

In [71]:
type(empty_set)

set

In [73]:
multiples_of_two = {2,4,6,8,10,12,2}
multiples_of_two

{2, 4, 6, 8, 10, 12}

In [75]:
multiples_of_three = {3,6,9,12,15,18}
multiples_of_three

{3, 6, 9, 12, 15, 18}

In [77]:
# union is similar to A union B in set operations
multiples_of_two.union(multiples_of_three)

{2, 3, 4, 6, 8, 9, 10, 12, 15, 18}

In [79]:
# intersection is similar to A intersect B in set operations
multiples_of_two.intersection(multiples_of_three)

{6, 12}

In [81]:
# add method add an element to the set
multiples_of_two.add(14)
multiples_of_two

{2, 4, 6, 8, 10, 12, 14}

In [82]:
multiples_of_two.add(18)
multiples_of_two

{2, 4, 6, 8, 10, 12, 14, 18}

In [83]:

multiples_of_two.add(16)
multiples_of_two

{2, 4, 6, 8, 10, 12, 14, 16, 18}

In [84]:
# discard removes the element from the set 
multiples_of_two.discard(12)
multiples_of_two

{2, 4, 6, 8, 10, 14, 16, 18}

In [85]:
# difference is equivalent to A-B in set operations
multiples_of_two.difference(multiples_of_three)

{2, 4, 8, 10, 14, 16}

## Tuples

1. immutable
2.

In [86]:
empty_tuple=()
empty_tuple

()

In [87]:
type(empty_tuple)

tuple

In [88]:
emp_tuple = (430020083,'Nanda','Govindan',405891583,'nanda.gnk@gmail.com')
emp_tuple

(430020083, 'Nanda', 'Govindan', 405891583, 'nanda.gnk@gmail.com')

In [89]:
len(emp_tuple)

5

In [90]:
emp_tuple[2]

'Govindan'

In [91]:
# Tuple is immutable
emp_tuple[2]='GOVINDAN'

TypeError: 'tuple' object does not support item assignment

In [93]:
emp_tuple.count('Nanda')

1

In [94]:
### count('item') find the number of occurances/existance of the item in the tuple
emp_tuple.count(405891583)

1

In [95]:
### index('item') will return the position of the item in the tuple
emp_tuple.index(405891583)

3

In [97]:
t2 = (25,'Nanda','govindan','nanda','govindan',25,'25')
t2.count(25)

2

In [98]:
t2.count('nanda')

1

In [99]:
t2.count('govinan')

0

In [100]:
t2.index('govindan')

2

In [102]:
t2.index('govindan',3)

4

In [103]:
t2[1:4]

('Nanda', 'govindan', 'nanda')

## Dictionary Data type

Key value pair
1. Keys can't be duplicated
2. Mutable
3. Hetrogeneous
4. Indexing and slicing is not possible
5. 2 dimentional

In [105]:
empty_dict = {}
empty_dict

{}

In [106]:
type(empty_dict)

dict

In [108]:
emp_rec = {'empno':430020083,'name':'Nanda Govindan','age':45,'job':'Senior Data Engineer','phone':'0405891583','email':'nanda.gnk@gmail.com',1:2}
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 45,
 'job': 'Senior Data Engineer',
 'phone': '0405891583',
 'email': 'nanda.gnk@gmail.com',
 1: 2}

In [112]:
key_list = list(emp_rec.keys())
key_list

['empno', 'name', 'age', 'job', 'phone', 'email', 1]

In [113]:
value_list=list(emp_rec.values())
value_list

[430020083,
 'Nanda Govindan',
 45,
 'Senior Data Engineer',
 '0405891583',
 'nanda.gnk@gmail.com',
 2]

In [114]:
type(value_list)

list

In [116]:
emp_rec.items()

dict_items([('empno', 430020083), ('name', 'Nanda Govindan'), ('age', 45), ('job', 'Senior Data Engineer'), ('phone', '0405891583'), ('email', 'nanda.gnk@gmail.com'), (1, 2)])

In [117]:
emp_rec.pop('phone')
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 45,
 'job': 'Senior Data Engineer',
 'email': 'nanda.gnk@gmail.com',
 1: 2}

In [118]:
emp_rec.popitem()
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 45,
 'job': 'Senior Data Engineer',
 'email': 'nanda.gnk@gmail.com'}

In [119]:
emp_rec.get('age')

45

In [120]:
emp_rec.update({'age':44})

In [121]:
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 44,
 'job': 'Senior Data Engineer',
 'email': 'nanda.gnk@gmail.com'}

In [125]:
emp_rec.setdefault('experience',21)
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 44,
 'job': 'Senior Data Engineer',
 'email': 'nanda.gnk@gmail.com',
 'experience': 21}

In [126]:
emp_rec['experience']=22
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 44,
 'job': 'Senior Data Engineer',
 'email': 'nanda.gnk@gmail.com',
 'experience': 22}

In [127]:
emp_rec['phone']='+61405891583'
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 44,
 'job': 'Senior Data Engineer',
 'email': 'nanda.gnk@gmail.com',
 'experience': 22,
 'phone': '+61405891583'}

In [128]:
student_marks = {1001:[78,69,100,85,79]}
student_marks

{1001: [78, 69, 100, 85, 79]}

In [129]:
import pandas as pd

In [130]:
pd.DataFrame(data=student_marks)

   1001
0    78
1    69
2   100
3    85
4    79

In [131]:
marks_data={'students':['Nanda','Karunya','Jayasree','Keerthan','Ranjan'],
            'lang_1':[78,87,85,80,83],
            'lang_2':[70,88,80,75,77],
            'maths':[97,100,90,95,95],
            'science':[88,100,90,95,98],
            'social':[70,98,90,85,90]}
marks_data

{'students': ['Nanda', 'Karunya', 'Jayasree', 'Keerthan', 'Ranjan'],
 'lang_1': [78, 87, 85, 80, 83],
 'lang_2': [70, 88, 80, 75, 77],
 'maths': [97, 100, 90, 95, 95],
 'science': [88, 100, 90, 95, 98],
 'social': [70, 98, 90, 85, 90]}

In [132]:
pd.DataFrame(data=marks_data)

   students  lang_1  lang_2  maths  science  social
0     Nanda      78      70     97       88      70
1   Karunya      87      88    100      100      98
2  Jayasree      85      80     90       90      90
3  Keerthan      80      75     95       95      85
4    Ranjan      83      77     95       98      90