## List

1. List accept duplicate values.
2. accepts Hetrogeneous
3. list is mutable we can change the value by proving the index

Use when: You need a collection that can change (add/remove/update items)

Example for functions and methods in List

In [2]:
list_1 = ['Nanda','Govindan',45,'MCA','nanda.gnk@gmail.com']
list_1

['Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com']

In [3]:
#append(item/value) will add an item/value to the end of the list
list_1.append('Senior Data Engineer')
list_1

['Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com', 'Senior Data Engineer']

In [4]:
#clear removes all the items from the list and make it as a empty list
list_1.clear()
list_1

[]

In [7]:
# copy() Return a shallow copy of the list
list_1 = ['Nanda','Govindan',45,'MCA','nanda.gnk@gmail.com']
list_1.copy()

['Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com']

In [8]:
list_2 = list_1.copy()
list_1.append('Senior Data Engineer')
list_2

['Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com']

In [9]:
# instead of copy() we can directly assign the list to another list
list_3 = list_1
list_3

['Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com', 'Senior Data Engineer']

In [10]:
# count('value') -- return the number of occurance of the given 'value' in the list
list_1.count('MCA')

1

In [11]:
list_1.count('mca')

0

In [12]:
# extend(list/tuple/set) add all elements from another iterable (like a list, tuple, or set) to the end of the list.
list_1 = [1,2,3]
list_2 = ['a','b','c']
list_1.extend(list_2)
list_1

[1, 2, 3, 'a', 'b', 'c']

In [13]:
list_1 = [1,2,3]
tuple_1 = ('a','b','c')
list_1.extend(tuple_1)
list_1

[1, 2, 3, 'a', 'b', 'c']

In [16]:
#index('value')
#Return first index of value.
#Raises ValueError if the value is not present.
list_1 = list_1 = ['Nanda','Govindan',45,'MCA','nanda.gnk@gmail.com']
list_1.index('MCA')

3

In [23]:
# this time it will raise the ValueError as the value ''mca' is not present in the list
list_1 = ['Nanda','Govindan',45,'MCA','nanda.gnk@gmail.com']
list_1.index('mca')

ValueError: 'mca' is not in list

In [18]:
#insert(index,value) Insert object before index.
list_1.insert(2,'Male')
list_1

['Nanda', 'Govindan', 'Male', 45, 'MCA', 'nanda.gnk@gmail.com']

In [19]:
# pop(index)   default index is -1 means the last item in the list.
# Remove and return item at index (default last).
# Raises IndexError if list is empty or index is out of range.
list_1.pop()
list_1

['Nanda', 'Govindan', 'Male', 45, 'MCA']

In [20]:
list_1.pop(2)
list_1

['Nanda', 'Govindan', 45, 'MCA']

In [21]:
# remove(value) remove the value(the very first occurance) from the list 
# Remove first occurrence of value.
# Raises ValueError if the value is not present.
list_1.remove(45)
list_1

['Nanda', 'Govindan', 'MCA']

In [22]:
# This time it will through valueerror as 45 is no more exists in the list
list_1.remove(45)

ValueError: list.remove(x): x not in list

In [24]:
# reverse()
# Reverse *IN PLACE*.
list_1 = ['Nanda','Govindan',45,'MCA','nanda.gnk@gmail.com']
list_1.reverse()
list_1

['nanda.gnk@gmail.com', 'MCA', 45, 'Govindan', 'Nanda']

In [33]:
#Sort the list in ascending order and return None.

#The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
#order of two equal elements is maintained).

#If a key function is given, apply it once to each list item and sort them,
#ascending or descending, according to their function values.

#The reverse flag can be set to sort in descending order.
## This won't work with hetrogeneous data type.
list_1 = [10,8,57,22,38,5,15,20]
list_1.sort()
list_1

[5, 8, 10, 15, 20, 22, 38, 57]

In [36]:
## sort() This won't work if the list contains hetrogeneous data.
##in this example it will throw TypeError

list_1 = ['Nanda','G',45,'MCA',True,'nanda.gnk@gmail.com',9884415602,False]
list_1.sort()
list_1

TypeError: '<' not supported between instances of 'int' and 'str'

In [37]:
# slicing list
list_2 = list_1[2:5]
list_2

[45, 'MCA', True]

In [42]:
slicing list in reverse order
list_2 = list_1[-2:-5:-1]
list_2

[9884415602, 'nanda.gnk@gmail.com', True]

In [43]:
# list is mutable, we can update/assign value using the index
list_1[3]='Master of Computer Applications'
list_1

['Nanda',
 'G',
 45,
 'Master of Computer Applications',
 True,
 'nanda.gnk@gmail.com',
 9884415602,
 False]

## Sets
used to perform set operations like union, intersection, union all, minus 

1. one dimentional
2. Hetrogeneous
3. won't allow duplicate values
4. individual items are not accessble using index.
5. sort the items by default

In [44]:
set_1 = {'a','b','c','d','e','f','g','h','i'}
set_1

{'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'}

In [45]:
set_2 = {'a','e','i','o','u'}
set_2

{'a', 'e', 'i', 'o', 'u'}

In [47]:
#add(element) adds an element to the set
set_1.add('j')
set_1

{'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'}

In [48]:
#Set won't accept duplicate, so the command execute successfully but you won't see 'j' is duplicated in the set_1
set_1.add('j')
set_1

{'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'}

In [49]:
#clear() will make the set empty by removing all the elements from it
set_1.clear()
set_1

set()

In [50]:
#copy()  ---Return a shallow copy of a set.
set_1 = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'}
set_2 = set_1.copy()
set_2

{'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'}

In [51]:
# difference(set) Return the difference of two or more sets as a new set. similar to c = {set a} - {set b} in set opeation in mathematics
set_2 = {'a','e','i','o','u'}
set_3 = set_1.difference(set_2)
set_3

{'b', 'c', 'd', 'f', 'g', 'h', 'j'}

In [52]:
set_3 = set_2.difference(set_1)
set_3

{'o', 'u'}

In [54]:
#difference_update Remove all elements of another set from this set
#this will not return a new set instead in the original set it removes the elements exists in the another set 
set_2.difference_update(set_1)
set_2

{'o', 'u'}

In [55]:
#discard(element)
# Remove an element from a set if it is a member.
# If the element is not a member, do nothing.
# in this example it removes the element 'b' from the set_1
set_1.discard('b')
set_1

{'a', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'}

In [57]:
# insertsection(set) like interset operation in mathematics {set a} intersect {set b} returns the common elements between the two sets
# Return the intersection of two sets as a new set.
set_1 = {'a','b','c','d','e','f','g','h','i'}
set_2 = {'a', 'e', 'i', 'o', 'u'}
set_3 = set_1.intersection(set_2)
set_3

{'a', 'e', 'i'}

In [58]:
# insertsection_update() Update a set with the intersection of itself and another
# instead of returning the result as a separate set, it right away update the original set.
set_1.intersection_update(set_2)
set_1

{'a', 'e', 'i'}

In [59]:
# isdisjoint(set) - Return True if two sets have a null intersection
set_1 = {'a','e','i','o','u'}
set_2 = {1,2,3,4,5}
set_1.isdisjoint(set_2)

True

In [61]:
# isdisjoint(set) - Return True if two sets have a null intersection
set_1 = {'a','e','i','o','u'}
set_2 = {1,2,3,4,5,'a','b','c'}
set_1.isdisjoint(set_2)

False

In [65]:
set_1 = {1,'a','ab','abc',(1,2,3)}
set_1

{(1, 2, 3), 1, 'a', 'ab', 'abc'}

In [67]:
# This won't work as set won't support list and dict as elements
set_1 = {1,'a','ab','abc',(1,2,3),['x','y','z'],{'name':'nanda','age':45}}
set_1

TypeError: unhashable type: 'list'

In [69]:
#subset(set)Report whether another set contains this set.
set_1 = {0,1,2,3,4,5,6,7,8,9,10}
set_2 = {0,2,4,6,8,10}
set_3 = {0,3,6,9}
set_2.issubset(set_1)

True

In [70]:
set_3.issubset(set_1)

True

In [72]:
# This will return false
set_3.issubset(set_2)

False

In [74]:
#insuperset(set) -- Report whether this set contains another set. all the elements of the other set should exists in this set 
# with some additional elements
set_1.issuperset(set_2)

True

In [75]:
set_1.issuperset(set_3)

True

In [76]:
# This will return false, since set_2 doesn't have all the elements in set_3
set_2.issuperset(set_3)

False

In [77]:
# Remove and return an arbitrary set element.
# Raises KeyError if the set is empty.
set_1.pop()
set_1

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [80]:
set_1.pop()
set_1

{2, 3, 4, 5, 6, 7, 8, 9, 10}

In [81]:
# always sorts the elements
set_1 = {4,2,8,1,5,7}
set_1

{1, 2, 4, 5, 7, 8}

In [83]:
#in case of hetrogeneous data sort the numbers first and then string
set_1 = {4,'d',2,'k',8,'a',1,'nanda','banana','c',5,'b',7}
set_1

{1, 2, 4, 5, 7, 8, 'a', 'b', 'banana', 'c', 'd', 'k', 'nanda'}

In [84]:
set_1.pop()
set_1

{2, 4, 5, 7, 8, 'a', 'b', 'banana', 'c', 'd', 'k', 'nanda'}

In [85]:
# remove(element)
# Remove an element from a set; it must be a member.
# If the element is not a member, raise a KeyError.
set_1.remove('nanda')
set_1

{2, 4, 5, 7, 8, 'a', 'b', 'banana', 'c', 'd', 'k'}

In [86]:
# symmetric_difference(set) - Return the symmetric difference of two sets as a new set.  
# equivalent to {a-b} union {b-a}
set_1 = {0,1,2,3,4,5,6,7,8,9,10}
set_2 = {0,2,4,6,8,10,12,14}
set_3 = set_1.symmetric_difference(set_2)

{1, 3, 5, 7, 9, 12, 14}

In [87]:
# symmetric_difference_update(set) instead of returning the result as a separate set 
# Update a set with the symmetric difference of itself and another.
set_1.symmetric_difference_update(set_2)
set_1

{1, 3, 5, 7, 9, 12, 14}

In [90]:
# union(set)   --- similar to { set a } union { set b } in mathematics
# Return the union of sets as a new set. Removes the duplicate elements first.
# (i.e. all elements that are in either set.)
set_1 = {0,2,4,6,8,10}
set_2 = {0,3,6,9,12,15}
set_3 = set_1.union(set_2)
set_3

{0, 2, 3, 4, 6, 8, 9, 10, 12, 15}

In [92]:
# update(set) - similar to union consolidates the unique values between the two sets and instead of returning it as a sepeprate set
# Update a set with the union of itself and others.
set_1.update(set_2)
set_1

{0, 2, 3, 4, 6, 8, 9, 10, 12, 15}

## Tuples

1. Ordered → items keep their position
2. Immutable → cannot add, remove, or change elements
3. Allows duplicates → (1, 2, 2, 3) is valid
4. Can store different data types (Hetrogeneous)

In [95]:
tuple_1 = ('Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com','Nanda','Kumar')
tuple_1

('Nanda', 'Govindan', 45, 'MCA', 'nanda.gnk@gmail.com', 'Nanda', 'Kumar')

In [96]:
# count(value) - Return number of occurrences of value.
tuple_1.count('Nanda')

2

In [97]:
#index(value,starting_position)   ---Return first index of value from the starting position (starting position default 0)
tuple_1.index('MCA')

3

In [98]:
#index(value)   ---Return first index of value.
tuple_1.index('Nanda',2)

5

In [100]:
# slicing the tuple elements
tuple_1[1:4]

('Govindan', 45, 'MCA')

## Dictionary Data type

### Key value pair

1. Keys can't be duplicated.
2. Values are mutable using keys but keys are not mutable.
3. supports Hetrogeneous data.
4. Indexing and slicing is not possible.
5. 2 dimentional data.

In [101]:
emp_rec = {'empno':430020083,'name':'Nanda Govindan','age':45,'job':'Senior Data Engineer','phone':'0405891583','email':'nanda.gnk@gmail.com',1:2}
emp_rec

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 45,
 'job': 'Senior Data Engineer',
 'phone': '0405891583',
 'email': 'nanda.gnk@gmail.com',
 1: 2}

In [102]:
#clear()  --> Remove all items from the dictionary
emp_rec.clear()
emp_rec

{}

In [103]:
# copy() - a shallow copy of Dictionary which can be assigned to an another dictionary
emp_rec = {'empno':430020083,'name':'Nanda Govindan','age':45,'job':'Senior Data Engineer','phone':'0405891583','email':'nanda.gnk@gmail.com',1:2}
emp_dict = emp_rec.copy()
emp_dict

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 45,
 'job': 'Senior Data Engineer',
 'phone': '0405891583',
 'email': 'nanda.gnk@gmail.com',
 1: 2}

In [106]:
# emp_dict.fromkeys() --> Create a new dictionary with keys from iterable and values set to default value for all the elements.
key_list=['name','age','gender','phone']
info_dict = emp_dict.fromkeys(key_list)
info_dict

{'name': None, 'age': None, 'gender': None, 'phone': None}

In [107]:
# emp_dict.fromkeys() --> Create a new dictionary with keys from iterable and values set to default value for all the elements.
key_list=['name','age','gender','phone']
info_dict = emp_dict.fromkeys(key_list,'')
info_dict

{'name': '', 'age': '', 'gender': '', 'phone': ''}

In [108]:
# get(key, default vaue ) --> Return the value for key if key is in the dictionary, else default.
emp_dict.get('name')

'Nanda Govindan'

In [112]:
# in the below example key 'email' is not available in the dictitionay so it will return the default value given
emp_dict.get('sex','nanda.gnk@gmail.com')

'nanda.gnk@gmail.com'

In [113]:
# D.items() -> a set-like object providing a view on D's items
emp_dict.items()

dict_items([('empno', 430020083), ('name', 'Nanda Govindan'), ('age', 45), ('job', 'Senior Data Engineer'), ('phone', '0405891583'), ('email', 'nanda.gnk@gmail.com'), (1, 2)])

In [116]:
# D.keys() -> a set-like object providing a view on D's keys
l=emp_dict.keys()
l

['empno', 'name', 'age', 'job', 'phone', 'email', 1]

In [120]:
# D.keys() -> a set-like object providing a view on D's keys
# keys can be assigned as a set as it will not have any duplicate values but it will sort the items so 
# best practice is to assign as a list or tuple.
l=set(emp_dict.keys())
l

{1, 'age', 'email', 'empno', 'job', 'name', 'phone'}

In [121]:
l=tuple(emp_dict.keys())
l

('empno', 'name', 'age', 'job', 'phone', 'email', 1)

In [118]:
# D.values() -> an object providing a view on D's values
l=emp_dict.values()
l

dict_values([430020083, 'Nanda Govindan', 45, 'Senior Data Engineer', '0405891583', 'nanda.gnk@gmail.com', 2])

In [122]:
# D.values() -> an object providing a view on D's values
# this can be assigned as a list or tuple.
l=list(emp_dict.values())
l

[430020083,
 'Nanda Govindan',
 45,
 'Senior Data Engineer',
 '0405891583',
 'nanda.gnk@gmail.com',
 2]

In [123]:
# D.pop(key[,d]) -> v, remove specified key and return the corresponding value.
# If the key is not found, return the default if given; otherwise, raise a KeyError.
value = emp_dict.pop('phone')
value

'0405891583'

In [126]:
# in the below example as key 'phone' is already removed, hence it will return the default value.
value = emp_dict.pop('phone','The key phone is not exists in the dictionary')
value

'The key phone is not exists in the dictionary'

In [128]:
# popitem Remove and return a (key, value) pair as a 2-tuple.
# Pairs are returned in LIFO (last-in, first-out) order. 
# Raises KeyError if the dict is empty.
value = emp_dict.popitem()
value

(1, 2)

In [129]:
value = emp_dict.popitem()
value

('email', 'nanda.gnk@gmail.com')

In [132]:
# Signature: emp_dict.setdefault(key, default=None, /)
# Docstring:
# Insert key with a value of default if key is not in the dictionary.

# Return the value for key if key is in the dictionary, else default.
# Type:      builtin_function_or_method
emp_dict = {'empno':430020083,'name':'Nanda Govindan','age':45,'job':'Senior Data Engineer','phone':'0405891583','email':'nanda.gnk@gmail.com'}

value = emp_dict.setdefault('gender','Male')
value

'Male'

In [133]:
# this time the below will return 'Male' as as the key 'gender' is already available hence it return the value for the key 'gender'
value = emp_dict.setdefault('gender','Female')
value

'Male'

In [134]:
# Docstring:
# D.update([E, ]**F) -> None.  Update D from dict/iterable E and F.
# If E is present and has a .keys() method, then does:  for k in E: D[k] = E[k]
# If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v
# In either case, this is followed by: for k in F:  D[k] = F[k]
# Type:      builtin_function_or_method
emp_dict.update({'age':44})
emp_dict

{'empno': 430020083,
 'name': 'Nanda Govindan',
 'age': 44,
 'job': 'Senior Data Engineer',
 'phone': '0405891583',
 'email': 'nanda.gnk@gmail.com',
 'gender': 'Male'}

In [142]:
emp_dict.update({'age':44,'name':'Nanda Kumar Govindan','experience':20})
emp_dict

{'empno': 430020083,
 'name': 'Nanda Kumar Govindan',
 'age': 44,
 'job': 'Senior Data Engineer',
 'phone': '0405891583',
 'email': 'nanda.gnk@gmail.com',
 'gender': 'Male',
 'experience': 20}

## Creating dataframes from dictionaries

In [150]:
# Example 1  single record 
import pandas as pd
marks_list = [85,75,100,95,90]
roll_no = 1001
student_data = {roll_no:marks_list}
pd.DataFrame(data=student_data)

   1001
0    85
1    75
2   100
3    95
4    90

In [151]:
# Example 2 -- two records
import pandas as pd
std_1_roll_no = 1001
std_1_marks_list = [85,75,100,95,90]
std_2_roll_no = 1002
std_2_marks_list = [80,70,98,90,80]
student_data = {std_1_roll_no:std_1_marks_list,
                std_2_roll_no:std_2_marks_list}
pd.DataFrame(data=student_data)

   1001  1002
0    85    80
1    75    70
2   100    98
3    95    90
4    90    80

In [152]:
# Example 3 -- multiple records
import pandas as pd
marks_data={'students':['Nanda','Karunya','Jayasree','Keerthan','Ranjan'],
            'lang_1':[78,87,85,80,83],
            'lang_2':[70,88,80,75,77],
            'maths':[97,100,90,95,95],
            'science':[88,100,90,95,98],
            'social':[70,98,90,85,90]}
pd.DataFrame(data=marks_data)

   students  lang_1  lang_2  maths  science  social
0     Nanda      78      70     97       88      70
1   Karunya      87      88    100      100      98
2  Jayasree      85      80     90       90      90
3  Keerthan      80      75     95       95      85
4    Ranjan      83      77     95       98      90

In [154]:
# example 4 -- update the row lables with the subjects to get a transposed view of the previous result

# insetead of initialising the dictionary with hardcoded values generating three separate lists using zip function
# 1. students list
# 2. marks list
# 3. subject list
# later assign this into a dictionary using iterations

import pandas as pd
students = ['Nanda','Karunya','Jayasree','Keerthan','Ranjan']

marks = [
    [78,70,97,88,70],
    [87,88,100,100,98],
    [85,80,90,90,90],
    [80,75,95,95,85],
    [83,77,95,98,90]
]

subjects = ['lang_1','lang_2','maths','science','social']

marks_data = {}

for i in range(len(students)):
    marks_data[students[i]] = dict(zip(subjects, marks[i]))

print(marks_data)
pd.DataFrame(data=marks_data)

zip()

{'Nanda': {'lang_1': 78, 'lang_2': 70, 'maths': 97, 'science': 88, 'social': 70}, 'Karunya': {'lang_1': 87, 'lang_2': 88, 'maths': 100, 'science': 100, 'social': 98}, 'Jayasree': {'lang_1': 85, 'lang_2': 80, 'maths': 90, 'science': 90, 'social': 90}, 'Keerthan': {'lang_1': 80, 'lang_2': 75, 'maths': 95, 'science': 95, 'social': 85}, 'Ranjan': {'lang_1': 83, 'lang_2': 77, 'maths': 95, 'science': 98, 'social': 90}}

         Nanda  Karunya  Jayasree  Keerthan  Ranjan
lang_1      78       87        85        80      83
lang_2      70       88        80        75      77
maths       97      100        90        95      95
science     88      100        90        95      98
social      70       98        90        85      90